"""ClinKey — Medical Evidence RAG · Streamlit UI.

A classic, multilingual, evidence-grounded medical assistant with light/dark
themes. The app opens directly into the chat — no login required.
"""
from __future__ import annotations

import base64
import datetime
import html
import os
import sys
import uuid
from collections import OrderedDict
from io import BytesIO
from pathlib import Path

import streamlit as st

APP_DIR = Path(__file__).resolve().parent
ROOT = APP_DIR.parent
for _p in (str(APP_DIR), str(ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

# This app is documented as a "zero-config demo mode" (see README) that runs
# fully offline even without the optional sentence-transformers dependency.
# The Embedder intentionally fails closed on hash embeddings unless this is
# set (see src/embeddings/embedder.py) so that *production* callers never
# silently degrade to hash embeddings. The interactive demo, however, is
# explicitly allowed to fall back - the same opt-in the test suite already
# uses - so app startup never crashes just because sentence-transformers
# isn't installed. This does not change behavior when sentence-transformers
# IS available: that remains the primary embedding path.
os.environ.setdefault("CLINKEY_ALLOW_HASH", "1")

from src.config.settings import ASSETS_DIR, get_settings  # noqa: E402
from src.embeddings.errors import EmbeddingConfigError  # noqa: E402
from src.history.models import Message  # noqa: E402
from src.history.repository import HistoryRepository  # noqa: E402
from src.orchestration.pipeline import ClinKeyPipeline  # noqa: E402
from src.theme import inject_theme_css  # noqa: E402

settings = get_settings()
LOGO_PATH = ASSETS_DIR / "logo.png"
LOGO_FULL_PATH = ASSETS_DIR / "logo_full.png"
_EMBEDDED_LOGO_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAACBI0lEQVR42ux9d5hlVZX92uece++L9SpX59wNdDfQQJNDkwREQFCr"
    "DRhHRUd0Rkcd02hV6ZhzHMVBcVTULhAlR8mhoQmdc6yuHF69/O6955z9++O+aloGERAM86v1ffXV19VV791379nn7LD22sAkJjGJ"
    "SUxiEpOYxCQmMYlJTGISk5jEJCYxiUlMYhKTmMQkJjGJSUxiEpOYxCQmMYlJTGISk5jEJCYxiUlMYhKTmMQkJjGJSUxiEpOYxCQm"
    "MYlJTGISk5jEJCYxiUlMYhKTmMQkJjGJSUxiEpOYxCQmMYlJTGISk5jEJCYxiUlMYhKTmMQkJjGJSUxiEpOYxCQmMYlJTGISk5jE"
    "JCYxiUlMYhKTmMQkJjGJSUxiEpOYxPMGTd6CSbxUYOYD66nzGWurE+D/tfiIePKu/XUfzh99dTCLgx/aJF78gv97eJ0XA/X/w0Pq"
    "7OwkIrLP/L8uIu6q/c7kbvTCFisR8cH3jJnFXqCtACgCqAB4ZcBFAMAFYsAUBTg1t2PQA4aPAIaIKJh4HWamToC6nuVZTbpAL/Jh"
    "HXRz267fM/bm3X0Dh4Z+mdOJ2J7lRy/9wzEOHiUii44OwZ2dPGkIf/JmUsdBi5OZaQuwaBQ4sVSuJv3Q1AdBOIMtxWDZMURxIsRA"
    "MCAKhZChlNIXEkyCijGIASnFsKt4MKbUumOBHiIK/+jZRZbGkwbwItDR0SG6urosM3v3ZSuvu+0PD1++df/wiSU4YAakDtGYdAuL"
    "ZtTfeMmFZ1xxONE9mDwN/uxGkmWu3wmcPDCWW5qr6lMDjUWhNQkIFYeQCiQcIiEcJStCoCKIQkG2KkkERChJIUPAVtnYvBQoE1EB"
    "ZAelJ3uSrrszBoydCGykgwzt5Xwe9H95pxpnnv+LR9d/6KHHt13WM1ZyQjcNX3qWmaAECEGZmkQVc1szA2ectPxb5y6ccm090Y6O"
    "Dhadnfj//jSYcB8nNpIHgGMH+8dXjpZLZ5asmS1VMqVUAlACmgkkJcAEJQSUYAgKjSIROIIKiqksBZeFoBIRawgEQlCZgBLY5hi2"
    "KKWoElFJklyf5LCnwXG2LiUqgpn4ZQqa6f/cTrVypUB3txlnPuaKux77xn1PbTptdz5ELNVgDbuCpBf9rvXhSMGSJDtBSUzxDE46"
    "ctGtrztjWddMokcAUEcHU1fXX88f/bs6QZnFhLuzlnnGtv1Dl47kym8pszwkcOIKXgxEBEWSSQmwZRABsJEBOIpIKAtPSihCVUHk"
    "BZmiZJTAqEhpS0QylJIDQVQFhM/W+kQ29KErRCjFhbMr7cq7Tiba+3KdBvR/8YHd2Tf6yl/97s5vbOwfO7TqpmzZMgGSPDcBTzpg"
    "ayAlwwLQ1oMjmKUuIKFLtGRmy5ZXnXnq586dmfkVEfHLufv83e76tROUmRO3FKpv39s/9JpA48jATTaHwgNIsoCAICIhBVgA5BCk"
    "kJAyioJ9zQishgLBlQxPwiQcUfQUxh0py0qgIhnjxqBkQ6OJOAQLBgGQFgxUWdsiWzOQijsbZyl11yKi/EttBP8nDKC9vV12d3cb"
    "Zk587fYHP33fI0/9y+6snwjjDdYqJaQrYZmgpIJkQDIgJMESYCDAJCCI4FrNMb9I0+PkH3/00v/50NlHdxBR/wvdfTo6OgTQCXTW"
    "ftB50H92Tvy7E11dXX+3p8vDzIft2jHwL6O+fhsnUnGjXAQkGCSJIOAQIKSEIaCiGaPlAkbGcxgZz6FYLKFcDeEbDQUg4QB1MQeZ"
    "ZAxJR9lEzEV9ps621afG2zKp4WRMjpJFoLUNdKCNJGkIYAgYFlyy1uSI+ImGWOyeFUS7X8rTgP4P7PoMgDf6fNR3r7j6C5v3D5+X"
    "tQ5C6VkDEtJ1AEUgEoAFbKjB1kJICeFKWAEwSQgoSGZ4YMvlvEgpgaVzG9eufM3Z3z0tnfwdEY0efMr8X4ubQMQdHR3izZ2d0/dU"
    "gjO37ez/YNmqZSLZAANYCyZyHLIAPNeBlIT+Qgmb9w6gb2gII/kyqqFGoA1ISJAUEEoi5jmIeQ4cAcSkgCMASQBYI6EUGhIeWjJx"
    "O396a2F6U102LsQwl20BEhUIaBYcsLElbfW4o1R/SjiPzHPw6Fyi6kthBP+wBjCR5QGAb9255pJH16z77q6h8elVr96WhCILIkEW"
    "DgGARRgGIAAKAsYYGCJIT0EoAZACsQMlXBitoSSYWDNVR8WcpkT5Na8886dvXjzni0TU275qlexeudI8hwvh/GbDvvO0qbQKpTQZ"
    "kJCCSYAFg0ko6yVjtq2pZeexSXr078nteRVwau948Z827R28JIw3pLXwWLICgUkIQLkKbkyhf3gcT63fij2jOVSZAKEgvTiYCSBE"
    "LhEspIr8IeUKOJ5EzJFQBAhBsFaAtWZiA7I+xYXF/OZ6HDJ9amVeQ8NwwsMuE9o8w5SZ4AuQsaENITCUcMVTjUrdupyo/JcaAf3j"
    "bVZMFGWIucI89xNX/PYTazZsfUdBJpSIJ0yZhdTkgIWAEACsRRgEIDAcYjiIHlLAgCbAdRUECUg4AEuQIDBrgBjMxipdEq2exTGH"
    "zb/9ne3nfXwR0ZMAiJn/KC7o6GDR1UX2m3c9+MbH12//YRlunSCAhIgu2zKYo5KEJ5SJIdx31mmnXn7pslm3/c1Trx0s1nXi+K3D"
    "+Q+v2z968aiISeHGbUwpoVgCllFfn0C+VMGDj63D+m17EJADr64BQkh4MQfahAjDKgJbgVCAUB4SyXr24g4MApJk4EpCTALEBKHi"
    "US4CACkJCQb5AVJS0CGtdVi+YNbgjIy3OaiYUWu4DDCEIEkkStroYQuztiEVv/6Mv/Ak+IeqBHcwi4n88M8e3nr+O7/ys+9u3jsy"
    "z3fqwI7HsCQhBAQMCIQgtAgCC4YLRQaKDDNby8wQQpAQEKE2EALQCKFk9HcUrVmAHOGLOI+yoQc27T6n57s/X3rF6g3/ftnxS39J"
    "RFi1apVcWTsNujZ1EwAUQ3P4oHXqxqxnFEGSIBAJYmYwGGxBjoZIBaX5vqmeBeC2v9XiZ2Y6/Z5O+Z3TsXxr//j7H905cHE2Xi/Z"
    "ibMHKYgJUio4cQdrN+7CA6ufwnC+BC/TCHJiqDAQkwyry2jwCFNak2hKt4QpT5nRSsXtKZaEtTmk65JoTCfRkkza5kTchtpgMFdS"
    "lYpPAYBCUIFRMeZkioraYkepjN7H1rUdMa0tdczCWftciQFjzbg1liA4QULETEXHijaI3cH8eyLKvVgjUP9Au/5EZmLap39z+3/8"
    "tPv6d/WVrUOJeqNBAiASJGFBAASq5SrCIICAgqNcuIKt1L5IeFLGXInRwjhcx4XlOJvoSUMTQwgJCYIgAYDhujHyYWBlwm4ZLU0r"
    "3P3IL7p+f8+pn7loxceIKHfgNOjsjLZ368lKyBwSYAlMTBDRUQAigAXBEDGsQ4KcbO0TEvDXNYKJzYSZxQ3Z4rse3tK7csRNC3KS"
    "7AAkDCBlDMYybr3hdqzbuBOxugbEE40wVkJaAcdqSN/HtCl1uGTFkeGR0zJjSWAsDgyXAbF5aGTGWDGfmTFjhki7rkMAO4CvgKoF"
    "8pXQ6EK5IvcMj87dNJiNjRsL48VQFYyKkbhry95kz3jxsFOXLZrWqNSQZOxjIglJTY7n1fulShOzjT/F/AsiKr0YI1D/QLs+37J/"
    "9MS3fOW/v75l3/CJ40bBeinLbKUlgoQCQcIai1K5BFgGmKHDKruwlnRBtiZFeNiCeTcfvnTJjtWrHzlp09YdJxZkPSXqMrYSmiif"
    "JwEmAQgBkAUzQykPmklQzLV9foEe3tLznncPdi+9fvf+j140d8bDRIQVHR3yXjAH4SPCWiJiAwgQBANgEEWGwBAIfR/WaALxKAC0"
    "r+oW3Sth/pr3tbaZqHuq5tI7H9t+6TAllEynLRkSxIBUDkJr8btrb8LO7TtR1zoNDIUg8KGhIUIBaUqY15bEG89ckZ/Vlg7u27Q9"
    "NTA4mKxvqJ+2bM7s/ctam++xrc2q3+KUB7fumtE/PCJdL56c1doczkgmORFTgy2ZVHF2JjXQnEkdft+O/c2jCJkpTog5EC0eNo/n"
    "Mbp6fea0xfNS85syCR2EWUmkYZEUXry+Wqkk9yvj72P+DRFVJgL6f3gDYGaizs6JXT/59dsf/bevffvHH+sbLSVDL2WMdITWWkhH"
    "gtiBsQxTqSIMAwgwBAmwtqy0oRjn5OI5DRtXXnDap9901OLraq8f+9oN9192xyNPfb4nO5JyExnjayE0gwQBLCxICSgmUGggpYC2"
    "VrCb4DHrmJHdQycP/uz6235438bvvefUxd8joj6gC1I82lCuhJDJqOBGQoABWGYABAYjDA18reG5shkAuleutH+DjUWtBV53x+r1"
    "/7mrImN1rY1sWQhpCcqNwZDBtb+5Fr37RpFpnQZWDBY+2qa3YsqMJsya1Yq6lMDiOreytCU9ctOmvhnd92x2jZJgHsWmvcOZd5x+"
    "zHhzqm7klsfXTX+kv1+lY3Fucj2EZd8Z8Hk6jD89CeCwhsyOZVOanhzMFU55aKgSByxrbQnCAdU1orc0jhse3yJPXLpo+rJZDQ2o"
    "mCFiW7agOut5LYEJaS9knplvAhDQP/oJcNBRxjuYj/mXH3Z3PfDE5ldlQ0B4aashJYMghAAZhjEBfL8MYxhCKigloDi0NiiJJmXt"
    "Wccs/cHX//nizxLRMNrbZXt7uyQiH8B37s+G677/wyu/uK1v7AR26jgQMcuwQluGgACxBCABI2AhYC0Tk5Yynra7x4bSV//2pk/s"
    "7e85eS3zZ48Atn/x9sebJBsYYyNDqqUaSETVUhBBUO0RRbW4v0nB8GPAtCvX7758+3B1WmzKPFu1EEJbJOIS1lrceN3N6O8ZRkNz"
    "G8p+AfGEh5NOOR5Lli1EKg1oC9S5wDSJYJ8fNj68aaeLWBrSTYBg7WilIKpEM/blivO2D/c70+qTOLSpkaZm0rYspBgKGUHo8mg2"
    "D1utLJjRWp+b09QyuK5v/5wcM4gBwwRtCeymUAqruGftThDNSyyZ3jiTtBn2JJXJOPFqNZg+XCidfl86uX8F0aMvxBX6uzOAjo6n"
    "A90f3f3UWz70yW99ZVPPyBRKtVirBIUwggEoIUEghL6PajUAswCRByGJ2S9b+Hl56PSG8hknLP+XT71uxZXfeB+A9naJ7m7T3d09"
    "4W6IUxuce5j5vI9dfcu3Vq/b/vahsEKh9KyVgqy1ZAHUqp6QNtrBDUKEAkJmmrnoV3DbQxtP27N/4Kp3vPW1t9U1Nc4LAx/CS9X+"
    "NnJ/GLWjBU93hliG/Kvf4M6oKnf3aPmSRzbuP3nca7YxdkibEJ6ycJXCnTfejp5te1HfMgXlahUqEcMZZ67AwiUzsH13P7Zt247x"
    "8VE0JhTev/Kc1HCxQHtHRmC9FpAhKKlEW0MDGuvSalvPQLzOdbCsucU/Ze6cq5sT3iO78rk3rssVV/RUgKqXxLApIh/4add1NUkC"
    "LIOYIY2FQbRpaOGAYwp3PbkFXuJIOS8Tb6mWg6xDroF0ppSqpaOFQA8zryUi//kagfr72vVXiq4uMsw84+M/v+ULV/y8+9L+khYq"
    "3WSN1gIkYGEgHQnWGtVQQ4cMYwBrDRwR2GoxJ1rqPHnS8kPXve31r/q3M2c03LWio0Pd29Wl0d1t1jAfvWvf8MLDZrX0LAVWU4Qc"
    "M7/zvxfMvePu+x793Lah3Lx8IMEUYwsiAwGAIGABMiAyACRCgKzyIBLKburPz/jCd3/xztapMw05CRhrSRDBWgaicAITLTlEgFIS"
    "IZuRWk2Durq6+K91sjLzwk/dsvqf+ytEnEpyqDURM+rSSTzx4Grs3LAZ8XgG2g9gHYOjjz0WCw+bgT/cuw5r1jwJQCAWj2N8YAyj"
    "JV8G0b2AIwUUSVgdgFQCBNSPBr4bcxTmNTWueWXC+3ciGlnD4XBfvnTsXmOTZas5wSEkCGU2sQIC+Eg+3bVkDJgYTIBhIJAx3PPE"
    "JjSvWC4TghqZ2Xc817WVQJbL/rFrksnlzPzQP5QLdFCga65eu+uiCz/x3S9uH8guLoYKIpnmwEIooSFMFNgaraFDC2MZSiqQALSu"
    "2iCfF4dMbwpee8m513zsvGO/SkRPYUW0+Jm54eb+/DsefGzr24dGsgt27ent2bNo/lXM/A0i8mu1hauzzA994Zc3da5+YuOlg+VQ"
    "USJjQ+0LQw4kEYh0VNGauBYBGJKCYhneXy6gd1evdOMpwAIsKcrtMCCIEL0HgRkgEjBGlwBg05Ilf816DF/bM3LR3rHKIdatZw6t"
    "kMYilYhhvG8Iax98FDEnBsEWflhBqiWBZccvwqat+/HYw4+BYnVwnRiEUAgpRHa8gpa2eniQzNaQ8ASYHOwbr+K6zfuTg8NDLI0B"
    "k80/veiUG4AoIAsdFNGajqE+FvN394+1Fn0f1s1EBTOroShydSsANDPgxNE/Pow1W/fi5CVzBFdsXOvQk8qN25AXjRSrF+xLxXbP"
    "Jup7PqfA39wA2ttXyS4iw8zxT/zPTR1f+/ZPPjTqk6udhIGnhAETgWCsgTEWVgM2tGAGlCAoabhSzrM0FXHKUQv2feC97/joK6an"
    "fktEGgBwb5d+POSzfvjk9g/tGR4/p+rWOSbeiIIOFxW27OwYr7bN2cb87UVEm4B22UC0B8Dbf3D343fdcOcD392bHcwoL2k1ucSk"
    "KEq4AmTlRGELBMC3TCqVgtUMA4DBEDVnhzgKgqMYwIKtBZONrOCvd8JOpD3bPn3rY2/O2hjcVB1DgDwArhW47/5HoKwDISSsIIRh"
    "BYuPOApuXOLJpzaCZAxKxWEsQEIDrMGVcjA71VY5rK0hs3UoD/Y8KNdFIbC47YF1iFEeF5x+PKa2tc2/G/jcH5iHdxh9UR84MZQf"
    "5zbPoaNmz8waIL5vrJiGFZBcJfZ9KLYwbBAyQNKDEC5CYoh4HVZv3oOpU1swI5MAaS0S5MWM4FmFqn/MUCq2BEDf3/UJUKMycHf3"
    "SjPOPG/lx7/+1Sf2Db+mKuMgL26ZhCQiEEfLKNQEHRogIChSUamdjS1nR0RdQtBFrzrjgU+84+JPTie6f+I9qsyH/HbnyFtW3f7o"
    "+3MkMmUnCWNdq0hS3E3wuC57G/cMXeYHOOI+zd8+VeJaivwb8b4zjvn5jTuHxn75q99/aevA8NIiYkwqaZmUsJYQRSkEkI0MQgiE"
    "WtcWfVT1NRYgIpAQIGtBgkAcGbMVjL9mCLyyOyrU3difPbdntHS4lo1MTEIyIRmLY/fWHejvGUQ6lgILoGxCtMyehQWLD8fgUBW5"
    "XBnCTQHkQEoLbcq8bOFMOnRa07ZWgQdffezi0x/pGTzkoW190DIBY0KwqeL004+nQxfMxWN9YwsH+ocXJduaMK4D7B4cggdFJy+c"
    "Z9uSnnm4Z3D2+r5BqaDQhBKmTE2HTakUDLMcKvpi53AO41Uf5HqwjgsfDh5Zvw0XnnYUEp6CDQikVF3Fr84ZKfnHMvN9zycWUH+b"
    "Xb9ddnV1GQD4we1r2l/7wS99ffv+sZmcaLDkKDKChAVBCAXBBO2H0KEFjICEAFvD1pZZV7Pi0KmNxde3v/p7Hzzv+K8QUbZWmKpb"
    "B5z/rYc3fXJLf3FpQcSgXMdKI0hACyILY4hYupwXMewa9U8olnbNys5oPHIT808XE20DQBfMb72JmR/rvOaOz951/6OX9eTzQiSb"
    "rHU8AQO4BEgmhMLCkgsmAaIAljUYDgQzBAiwJnJ/tAULiUqgYZwQLMB/pd2fart/5usPbXvjsPGkTLiWLBORROgbbN6wCa5yAMdF"
    "QBbJhgYsOGIZ8saCyIIcAY8I0iFYBqAFGjIpzG6u23RYKfivxTOa7jLADx7d1NNcDspsTZ7OOesYzFk4G7dt68OmHQMUaED15Vlw"
    "iEZP0CXHLsXUtCfu2T/UfPeGbUCgceahi/j0hdP7rYCthlpaQSkjZWqpb+ihDXuxfSALI1w4iST2D2bRN5DFopYGBNaHq4RkpZqL"
    "peD0x5PefQAe6IwO6L8PA5io6HZ3d5sq88L3f/XKT33nxz9/y7jxhEjUW01CCAaIBQQIrA1CrRFWfRhmuEJAmaoVuiri0qcTTjpy"
    "9bve/ZbvntGWuoaI/N8ND6ePaW4+5rrekUvuemz9m3eN60YTy9hE0iG2LCxs1LFd880lmABGkcmyL6bltvV/aCRbOuEBzT88WeJG"
    "IioR0RAzv3/BzBn3rrrxrs9t2Ds4X6uUjdU3UgAQDENJgFhDmChUZhFRrQGO6gm1CgBYgCzDgazdeF0GgHYA3S/jfZ9Ium4GTtkz"
    "MHZC1ToQmkkJC+UQ9u/di+zIGBJeEgYW0nNxyNLDIT0XPfv7MHP+LKRa67k4lEfKcUkTI0w6vGl3L937SHLp/BMOm9sHLLl/zYbk"
    "4PAYEI/TiScvw6yFs3Hbo9uxee8w4KThSoUgKFJaapy8bCmaGlO4d+cgnti+C5UwwBlHLsZxc6Ziy+Bo/bqd++OFaoDAaEo3pXHI"
    "grk465h5kE/uxqaeYcBNoEIuNu3ow8yGBrgkYZhBJBKlIJhaqJqlAB74c+xd9df09WvuBX/rhnvOP++fO7+za7Awv6rqECjHwkBI"
    "wQADrBmsNbTWILKQksAsmMPQurYqp9Vx9vTTV3zrS+967RVENFAzrsRa4M1XP7blske37Vs2HAqYWL113LiQRsORAqilTiNWTvTd"
    "Wg1NUlRJsSvTXmm0evp4Ycei8TlTj9vE/KPFRNtq1/2rcebVX/ifm7/1h9VPXjhYHAGlGy0LJUImSGMQNUQ5kWcjorSPYK4FvQBg"
    "IYSEIwWEZSTTMQ8ANra0vLxBMBHvZo6tGRh/1f5SUO+LJDvWIUGAlISBffsBrcEeEBiN5papqGusx8BoP3ZseBQtzefj8MPn0aZH"
    "nwBXsmCWIHIpV67iqd375uVPOOy1Nz3y1EmPbNsf963iBTNaadlR8/Doun3YvKsPIp6BkAq2WkZKhjjr2MOxoK0BD+4dxtp9Q/BZ"
    "4ojDFmHJnKl4sq+fVm/rSVA8DWQyCLTFUDGP7IatuOiYpTh6bht27OmHZgEv3YD9IzmMlSpo8VzAAgbCU4yZuWJ5ySDzlDaigedy"
    "g9Rfb9dfaZhZfuQH13ZcedW1H+krIs7JZhOyEsxWeBKQAGxt14ehKBiLfGdLfknUOyyXL573+DvffMnl5x4ydfWX333gPZLX9WU7"
    "735s07s2jlbqSyrB1vVgrRCsLZSKIlGjDYwkeELBMkHXeDpCKFhICthwSAo2DKeVtvW8f7gtvXQ18zePJ7r1sh+tceqJdjHzpb84"
    "auHlv+i+5d+3Do40cKLFWjdGBkxWRNQJgogWvgUsGEIIMEdxgWULKZi0sWhsaprNzA4RhS8XI3Si8DUHaFy1b+SY/gqgY4phJBFr"
    "yEoZYwODUELBsAWkQiKdQjUM0NuzH8HoGHoeX41/esMry6fVHz2+eU/P1Md2D1OhbChkgq+kNwyc/uSe/VOyIcCKaMlhc5Ar+Niy"
    "az9SmQxIeVBaI50CTll2GBZPacATPUN4cnc/ShaYP3sqjlw4E5uHx7Bux164yTTHHBcASJLDbryZ/PFBDGULaMrUIe06GLUELR34"
    "GtjVM4CWRbPg+yGYFXuOmynp8MghYD6Agb/ZCdDR0XGAx3Pto/uOPftdn/zP9dv7z9FuCkhkbGCFZLZwFaBMCM0MawnWEJRwIKyB"
    "Q9boSkXOTlP5gjNP/s7n3nHBd4iov71jldvdtTJg5tSPNuz99h/W7vyn4UAgr9LWSiUUgBgJUBjCsAAxwWELhoQVDG01BEuQlJDW"
    "QAqGlJYsASV22Idwy73j55QK1Vl3V8PUGTHnmmgzpQKAL21gfuCKK2/41Oote88brBhYL261tQICB3hJFHlY4FowzBZgqwGyXAbR"
    "Y2s2X3LoWcdt3Mu8JqJSvAx9r1HdC/uA+fuH8vNLWsBhQQYMJoFSLodyoQRBAlG2jRFPJOCXKyiNZZkSSZqdittjMu6PlmZmdj8+"
    "f/qH8MDa9gc2DDAxSHgOZYEZI0YA8RjiMQHpCAwMjcOJe2hsqIc0BmkhcOT8OVjQnMaWoSye2jOKsjaYPqUJyxfPxP7RAh7bsBPk"
    "1aHFdWhe2kOayI4GJPb5GgUnjkI1xPw2ByoMIBwLC0B6LvpHxlCdNwOAgCEJTQquDuYXgUUAHvybBMETgS4z13VcddvHPtX5+Q/0"
    "56tpxDIWyiM2LAgaUgAwFhUdwlgGpAKRgJJgpatwwoJcNGvqvpUXv+ryy16x7Mb//CcAgOzuWhmMM8//2gMbvvPgzoHze7XHwksA"
    "JIW0BoI1SAp4jguCAFlAiGhRWsNQSsJTLgABEoCgaOfW1kAzk0OKoZLYV/QPLT657Vu/G8jNenVb3ZVElFvR0aGWEj3AzK/+/j1P"
    "XX7rfas/tTubbypAGSglaySgA+EXwwAUcbRYAFYIKlmJG+9dc+zevf0/Ouf0k68fYv7FRuAxIqq+pJ1nnQC6gP4AC4fHig2CPRhj"
    "EAhCAg5GBofhlytIJFMwxoAVgS2jWixBVwPImIv6hgbKALubiB5ew3wUhaZ9ZGQM2ghIL4YCgPHAwjoKXspB7/AYvGQKs5ozSDjM"
    "SWZaOLUFc5rT6MnmsWHXfvSPFjG9tQ7HL5mN4WwZDz+xBSwkWj0PR7U12iWN6ScaXLVmuBye+OhY6YjNgU/VwKCZMDQ77TVms0Xl"
    "JhRIOciVChivhEh5cWjLMAy42jSX/HDqXz0NenCg++CusdkXf+CzVzyydvs549qFU9dqDFgKABIaAhZsCZUghLYMJdyo5iqN9YsF"
    "0dYQw7LDD/n9Jz75/k8t8WjjMZdd5jx+xRUhM4ube4qv/9Sv7/vcU0PFeeV4nTUqJpQV8KSAq6IgtxxWkc8XoEs+gsCPGvsQtURK"
    "AmJxD6lUGslkCqlMHdy4B8eTSMU9OATyjUYoXGuMnl7duucL+ULzETuYv7eAaE10GJAG8M37RkoPXfWbG7/9+O6h4wthaGXMQxAa"
    "IQSDSETkRKIoFSEBC4KVcfgyxmt29k/p6fvtZRuOOOSQC1+14gqOWI2GD+p9eCkwOlJMlMtWkImOWWMNtCCM9w+CrI0qrdaCmNHX"
    "04NYPA4yTK6K8dp9/XTD2q0ffIo5uXm0eMH+oTwcFUexMA4DgbwFioGFEQDFFHqGxzALEnNb4sh4iqbFlW2rc814ftwZGM6hEgAu"
    "Qpy6bBHCcoj7HtuIbFmjJe1wikOakUoMtrnqDsdgQzzhmD1l7/DNVtPw2Ci0nrLjnOMOz/Q/sHnJfr/KFqBSxWKkEEKJBAxbskwI"
    "INzAYO4+5sZZRGN/6mRVL/WuPxHofvyH177jny7/aMe+4fxsimesisXJhKEUThzWhCA24DBiy0BbONKFNIYFqmz8gli6YFq+/bWv"
    "/OYHzz/h8zXFMKot/ulfe3j9Nx9cv/e1e4pSaCdhJTnCdSSENqjkxjFayKNcKqJSKsGEBgRiijIErATVyGlAURKN0Hi0OMmSdASS"
    "SQ9N9XWYNX0aWqdNQ11dSvjlPI+WhFcZKL9taGz7ilW7+77aPmfqz2vukDitObmamc/tvOmBb95935p39OdG4cQzxhgrrRBgiirB"
    "kgQUSzAxLAhFzeTIOA9Uqrjp/idWbNq597D2V501j5l/SEQjE11mf8kz2VTL/+fHS5kKS2gl2EGkuia0j9LYCCRJhNbCOgIKFoXh"
    "QeSEiIJ6rWjPnhyuCTfNa56/8Atb+grUN25R3zyFyrlxVIslVBgwZACWAMcgSCD0C2hWSRzb2rK9MSbv860/PVcsnOG6jtfWmMay"
    "w2bDcR3c+uAGjOR8pJJplPJF2l8ax9DUhoaZqbZjQommfeXyio19vWJgPM+FfJEeVOtnnrt82UgiJhCOVIliHqrVKsbLFTRkMrDa"
    "gEhxKONUqobzVMJJAxh7WU+ACR5PTZkh84Z//8rnr7rq5+8bNy6JRJMxpKTkiEtDoQ9iRmgtmBhEDCklCJZ1pUQNSUXnnHvatndf"
    "9oZvntzs/GJCLo+Z628fLV30L7+58xNbRyuH9PsCKp2xSeWIsFpGfmQQ+fECcrkiCMRKCHYsswcWUlhia2DZkpQC1jKkjDpWBCmQ"
    "ELAURbCFoELj2TLt2jtEbY27sHTJQrRMaSYRT3GuXEW57M8Z78t/fzBfPe/+SuW7p8RiDxJRucYneu/c6VNX33Tb/R/etG9koS8U"
    "bCxlAwhhrQXBwEKDlQQLCSEELEsK4MHEHLuxL9c6cOVvPrvllOVHM/PHqVaPeGb75YtBoVJOaZIwLFjVWHgmrCIolyHJhWWGsAay"
    "Vq8gN3JFOdAwDjBeMTwUCurJVVEoW8gEoJQLMIEkIIStxT0KDkm4gtEUcyozYs71cY37jIpPCdKyrsjhSfGM4FRDnB54chf6RnJw"
    "vRR0UIW0PhYefghi09tiTw4Pn00MvXWk4K7rH0MusFQqBcgW/eYykBjPl+D7gDVVBH4VxVIZYY12LiE4JEkVXW0oAdMB7H3ZDOAg"
    "9qZZ9cCmE4+75H1f2D1YOD1AhmUsbgMrJQkZ7bpgQFfBFFGMGSK64Ta05UJWLJk3zX/rpa+94bILj/vvJyOiWomZBYDZP93Y03XH"
    "I+vfsjsXouKmrVuXIBv4or93P8YGBkGaoaRr41BgDkSMDdXHJJIIEHc4V5dJa1fKkpJOTnkyFerQ09bIILBOtRrEA23jPrkoGSCQ"
    "HkIhbano0x/ufYTimRTmzZ9D82fPBsdjdjAIRVDxL7Tb+5aPTW/r3sD8y2FgExEVAfyIma//1K9u//IfHl7zlsGSFm6ywYTWSsMR"
    "SQKhghRR91ktOQoIJUTK4/5iHr+9d80lvf2Dh97Zn/vY2VMzNxARXmxc0L1xIwPAeCkf1zoEQ8GGGhASOtDQoYZyncgN0hYgQmgs"
    "YPxIRkYphEEIgziVQ3ChYqhUCZByACIPmiRsjdlNBEgSkEScdgTVu2LYAfYmoUt5UC4m1UAMIQhM23sH0T80hmQsjZANmH0sW3Yo"
    "lsyfhsf3D6B/T49IxVLuSAWc1zEKgzK4VMKCRceKPWPlZN9QDgZ10EGIUDPG8wWE1sIwQcIiYI1qqD0DxF++GKC9XdbYm86Hv3Xt"
    "uz7T9Y0vDYxX66xXZzUEGUghos50wBpYNgjCACQ9kCC4UlpbLZCnQnHiCYv7/+Xf3vndi+a0/mL5e94z8PgVV4QA8GiAt139q5su"
    "X7Ord/m4TLLMtDLIEfnBIfTu2g5rDJSIWWEY0i+K5oRCcx1V2hqSj8+e1vrw7Nb6B4846qit86alw1lADkAWQCMipWI5BHird/TV"
    "7dvXs6x/oHB4/2j2tIHxwqFjlWpiqEKIJTPWDyU9tWE77d3Tg6WHLBKz5sxB2QoeEmJqee/I+8bHy8unT2/57VPMv72us3NvTUvo"
    "rVc9vOHua266+3O7x0amSxlnduMILZMIBSxZSAk4StV4QhaaJIlEA0KbtA9v7Tts6KprV3377ie//y+nL+skomJHx92qs/N082JO"
    "A19rqa0FCYCNhSBA1LhMUaXMAEzQoY9p82Yjlkhg9/YdEIEPC4MwZBRCplJgUPUNnHIAS0AARtUyDEc1HEkMxQYJqZBwZTUEpo4p"
    "FQbAorwJjyqYAGMln0dyOUqn07ClAGExh6VL5uLw+dOweyCHex7dgnrPxXh+nCuBJVMOwIVxHL9wJlqb6t3f3raaiqUQHEfUCGUI"
    "+UIZVWthwVAMhJYRsnEDwHvJDWAi0EV3t9lW4fkX/+sXv/7YU1tfnfUFnESzDUMjLAhMgJSANQah9gFYWBntNjERWlMaFU0pwpln"
    "nND9uU9f/sPZ0a5fjt6CE99/eMNn/vOrP3n/lr7xJKcy7NUnEZR9MdCzA6XRIcSkYM/xrK1k5ZSkwsJZreuOXjz/FxdecNpjy1Nq"
    "NRFV/sRHGH6Wnz0xUVO4e7iy/P77Hlqxbm/Pm7cNDS3M2TigErZYCcRDq5/A/v4hHH/c0WSEy2OSVFjWJ43v3D9vbmv90os7O39/"
    "YeeHH1hOdSNvP3HpT9cyr/3R93756cc27r54pOpDJOoNRMRz0kajpjp3IEhmQ9DkCFHXZreNF2PDdz7y4S1btx6zmfmjhxGt6ep6"
    "WoHihTwzSZLZGIAtyAIkowLdBNW4VrEAE7D4yMPRNmM69u/bBxOGIEUIDaNSNqj6FlpbgC0qQTnSVWKCCS1gDEj7cEnS4tkLbH2y"
    "Xo1qe6pvQicbBAsGK35TX6mCsiVyZRwuVeCgjGOOmIdD589C73AB9933JIIAOOGEIzA9LSlydXwkBWHZ7Gm468E19OSG7VCZGagE"
    "AUgICKtgQkaoLbQlGGbymGHBQtck2V8yAzg40P3kj6577Rsu/Zdv7+gZmR6KBItYEn6gRVTQtRFBLAwAa6LGcKHgCMHQVcuVvFw0"
    "q6nnda+96LOfftP5Vx68q+1gXv7hn9/yxfuf3Hr2UIXgZKZYVkrks3kM9fbBVstISrJcKohMOiGPPnzWthXHLP7Ov5x30s+IqPjZ"
    "g6rPALB4VTvXMoJ8MDGks7OTJhpENnV3U3d3N4ioBOBeAPcy81VfvvO+t927Zv3lO7OjbSUkmWQMGzdto7HhYVz06vPJTSaRCyus"
    "iaYEfWNvGi+FS2ZPa7h6O/O1Czs7e48keoKZX/Ot2x/9wG13P/TZvWMjmSCRscySICQF1kJKhZoQGgRHfcNVA0Fegse0z4/tHDj9"
    "k1/60Y3fe2DDpy8/ecnVRFRCR4dAZyc/3/5XSYKFjU4agA4Q90gqMDjy5Ymi2kC1AgNAKgUOfIAFbGBRKQUwxsKYEOVKHjNntuCc"
    "FUdh96Z9KAwW4aYEwtwITjz5NMyb0kIjZT2zt39wbkUR5axGsaoRGIFASLAFUgkXM2YuxPQZjRgeLeO++9YimwvhOC4GBkbRmmhG"
    "a3MDlBAQ1qBsLBYtXogH1vWgoE3UbqQBDgiSXGjDCDjqD/GtBguC+DOUwxdqAFQLdJte95EvfOEnV139zrGKlDLRYIwlScZAwkZk"
    "KWYwRwxIKwhWSCglrQ0qojEh5IlHH3/7F7/ykX89lGjLZy6NYjJmTnU/tfNNn/z8f3es78lOq8ikNfEEGc3CVMYx0rcPwmh4zDas"
    "VMQhUxsq55123H99/m2v+gYR9f4rgPZVq+Ti9nbuBLhmqAfIMF1/zI2JyDpdXf/rdOsEqKuzE0S0D8DndjBf971f3fTF+9fuuaAv"
    "X0FbIm7HBobENat+iwtecwEyDUnydZml67i9+eKxhWKpxc5ure/t7Pz19K6uLbVeg++syQWPfu37P+nc2Jc/N4QHmUzbiiVhrISg"
    "iKBhJQEwYGsACIKQVPHq7Y6xSlvpzoeu2LNn/6X3jFQ+f3pz/A50df3Zwln7piXUDUAS+UooCMORMJWxgBJQjoSxBMkiWujGolSq"
    "wFEOlFTQ7EOwgPUNglIV0AaoluBkYrj09WdB2Cqu774JXFUwXMLxJx6HI2e3IutrenLXPqdQLkOmUwzlQCqPlCPhuApNqSQcR0E5"
    "hL17c1i9egNGs0U4bhK+Jjz8xHas3bAFruPAWgJCHzOa6/DaV56EBfPn4IE1u5BIZ6LiomFIKGhjERoLY23U5BOHdZ/uSv2LDGBi"
    "4+Sv/eoPr19+yb9+euu+wSWWPMSSGVsxRgoBGKNBbEBMYEgYJsACUiiWMNaUcnJWc7x60avP/+o33nvJ52oZHlFb/Av+47r7vnL7"
    "fatfPVoWguON1jAJyYz86DDyY4OIOQLwfevokjhu2SGb/vltb/7Xi5dMufMLbwcOGnBhDl7sL5w2M9HCUqNsA1hAtIGZL/rvedve"
    "fd0d9395y/6h+oZkoykUK/LmG27BRa+9EJm6NJXLBSYvhdHQn7NmT9/7izOmTtnO/N2FRBvR3i6XZ9xHmPmij199R+fqRx//0Ggh"
    "jJFKG3biMmADKQwUce2EEhDEsGzgkxAyluT9hQoPPrxhRc/+vsN/uWHXJy5dOu+K5xsPiEgKGCST0CAQW0gVg5esQzFXgMMAWYIQ"
    "jKBSBRMQq0uhmCvC1RaohiiVfJTDECLhYvFRS1GqCKz68TXI9wxCOAIXv/FinHnKEvRnS7j5/ieRBZBMpmBLBQKJSGqm9j2eKIAJ"
    "GM8VMNifRaXog6zisFJFjBwyUCiECjrQMKxBHCA7OoDDDhlAXVMj/OpmwPhRytVUQE7UMKMNQVkBAiPhqUIDsHuiDZVetAF0dBB3"
    "dsr3dl3xue9/74qPD4wbiHjGCEmiUq0IUhLW1h4aR0FvJARlIa21DqxQuiqPO+qQXa959Rnved8Fp975zX+GmGjU+N22/ne3f+7H"
    "n9gwlJtdZBc2lmBrIGISKGfHUBgagudIcKlk6h0jzzvz5Fuv/PDb3kdEu9HeLjsWr+KuLrLU1YWXEhPSizVKBwO4YnWO+7591S++"
    "v3rr/llxN22r+ZK48bpbcNqKEzFr5jQqhwFIOlYqp2nfYPZNxk8lHmP+0bFED65axbJm9J/88T1P3H3zHQ/9cPvA+LwClVgk4jAC"
    "JIEarVrCgkGwgDDQ2hCkQyJRb9ftH2oc+vk1//W12x6a9+FzTvwKAdk/pWC9eHHk/tVnMhUyPbBCE5EDJQgkFOJ1jcjnimCDSJyZ"
    "COVcAdYCmaYmDO/qhRWADgSyhQLcujosPe5Y1Kfq8ZsfXovB7XshPI2Vb7oI559xBHYMjuNnv74NZRmD29SIbCELAqCtqXUSUcSV"
    "IkLIBlU/AAUWMUOoT8RJwCCbL0BTDKFWsCHAZEEOwQ8NSr5FoBlB1SKuFGBChEEZdXUJUK1tUrKANAYpL757ynOkQJ+XAbS3t8vu"
    "ri7z8cZDL7zttts+3j/ms0o02lD7EhYR7dfUClrgiFpAChLM0obWBgXZWKfMK15xxs9+0vHuLxLRDhxzjIPHHw+ZueWLv3/wi9ff"
    "9cg7t/TnkWidYq2UBCYSBPjlEkrjo0g4gPB9k5Ravvrck6/+/uVvfD8RZSd0OrteZoXH2oAIOr3zHnV8hm4cYN77ke/94qf3rt1x"
    "jBUpmw1Z3HzDbXj9ylejrqEOjoiKDVUh0n2F0qtKod9wexj+1zkO3QwAKzo61LtPP/qOceZzP/29az79xJadb92fL4PiacOAtEJF"
    "Eo2IXEpiAyIBzQ6skIJi9XbP2IC4/tY/fPiQQxf086yW7xKRfS5NnDlzpw/VxzbxYKEsKJ7BRL9ypr4Bw739kaCnBaSQyI3lEZQD"
    "ZOqbI0EvjliilWqAeH0d6oTCxjvvx8iWLVCiiovfcDHOe8UJ2Nk/hh9deS1yJQFRB8hUBfPmzEI6lYKxBmw1mKNMjeVok3SlRJIE"
    "pqfivLC1PhdzlPjGL2+r2zXQj3iiCUq4sABCP0DCUWhracG9G56Eo1xIIlhYxFyFKS2NEYUeFqEuk4KPunjjeqoN2HjRbNDu7m5m"
    "ZnrFWz/w5t6hMXbT023AtfR9zcdnjvSDBaI2QaFgdTkn4srIhXNat7a/7pKOT77tvN/8tPOyyJ16/PHwsWzl9Dd96cqvPLZp37HD"
    "gWKZmcJVlkJyxKQEWxRyOZC1kDAmZovy3BXH/fb7l7/xnQfxZczzyVh1PocGaufTX885Eab2f3rVqlVyCtF6Zm5/09d/et1d6/ce"
    "GWqy5aoWd9xxN1772ldDSAKDSCsHoeM1FtlfEfQOO7/L5tpm1NfdsJxopOPuu1U90Q5mfvuP79n4wI333P+5TT3DbaA6K1yi0IIg"
    "CYYj2gYQNaaYENAGwos3mZHcsLrzlrtOuuA9b/jenzrmOzvBXV3A3IyzsyXtDe/KBa2WmZktaW0QT9VDKQ+kJ9KYCtVSgOJ4EfFY"
    "CkJImCAABxJcCgCqYP1TazG8cztgSrjoTa/Eq84/CfsGcrjyimuQHQ1gVQzKD7F44SGYNnUKyuUCHCWgJEEKgpICrlJwHYGk4yLt"
    "CMxIg6cAu+JA6ZWnHnnK1Tc/SKVSFoElWLJwEwJnnXY6jC+wdfNeKFLQQQCrK6hvSqI+UYdC5IIzmzLFUa22xdyev4gLNNFJBEBW"
    "K8FsZkHGMEXOS1T4AEf5ZKrl+l1H2dL4gJjWksHJp534s19/6d8+TESjtffSzFz3H7+48UMf6fj2h3aOBXUVkbIUd0nbQLgiDkkM"
    "YQwK+RzADEfCxsHy9FOW3XzlJ955GRFVOzqef1HoYJ/+WXf3Z3z/s62FK1eamiuzexPze/s//q0b1/RmG9ONzdzT20+PPvI4zjrz"
    "ZIRBEZ6KIzDMQnppIjoxX9Ate3XlyAeZ//tkog3R9XUS0PXjHcxPfuuKazseXrvtgmJVQ8RTXAkNCSlgI8VSWBPWPpOAMSAOLe/b"
    "2zu/VtN4zs1gDvDU3JktO9fu39NasZYtQIYYjpuAcDyYoAKJiDVrA41SqQLX80BCQZAGa8bwtt0olvIojw0CymDFBWfhnNecif2D"
    "OVzx3V9icLACcpOQMYkTTjoZNnBw120PwK+W4bkKStaWDgEMCbIaMAGUYKQ9Eicunn/o8UcuKqZbGugNb34dBgazyBdKsLBomdqI"
    "hlQKd9zyECr5AKl0PazW8KsVtLXNQyzuYiznQ7Blz4bUFFc75wMPAEAHQF1/Yg2o59FJRABsKZcvOYJgmRlsav5pJEwFYyClZROU"
    "ra748tjD529882Xv6nr/ecdcU1uAEoB+ZIQXv77jv3701NY9p4xpBybeaDVLIUBwBYO0BknAr5ZhdQiH2LJfEmecfNTGX3zqn97z"
    "gjT6a+4AM6efAmZVioGQSkyzBGlM4FgDxyeSjutyxpW9BnhyOVH5+UjrrVxJZtUqlouJHvn5E1s+Hq665cc7i9oilsL6Ddto3rw5"
    "mDe3DcZaOCAyIITKq4M1h5NvG/ftG226abR84/mN8RuJqPSjNWucBURrmPk137z90Y/feMe9H9ufG04qN2k5qhkDUGBoGERpPhgD"
    "JQluzOHnsQEQgLHDFs64+56n9p9YsYaIJGAI5HpI1KWQzRUgHQ8Tui3GGhBHlGmGhLCMbP8gLAWA0Djz/FPxyteegb7+Ufz4m1dj"
    "fKwCkh7imRROesUK5IpVPPHgelirkUwm4PuMoDYAxhAhQAgOfFaSIFxFA6UA+x7cmrhlza7EeDGLlpkz0Dp1OpLJGBzHgSaJO+96"
    "EDvW70DcbUClXIGUBFISM+fOQdE3CEIDKSySoY9ZU+tXZ4i2ApEM5IuLAWqLl4jMCa984y4Bu0KQZT3Rz80EAQUhYINyXtQlSJ55"
    "9tk3dH/1399LRH0fqEm7MLPtfnjnez7yoc/8x7q+7AyvrsEa4ZIOtCBHQAoZyYxIwA80/GoAtmC/WqIl0xqrb3n9BR8hov2rVrFc"
    "+TzcHtRm2TKz6rjrns7ecfPOcrUihJQSkgRHrbwgQaK1qYVn1CX3L547/dvM/F9RcfP5GUH7qlXyzUcdcuX2Pf1H5R/a9L5hJGzV"
    "GHp4zTpMm34uJAxYGniCoA0DTA7AMzxSp2SL5WnXVfxZm5h/sZioP/LAKATwuRt2Daz9n1U3/HD9vpGplVBaqTwitmRYR1VcS4gp"
    "waSNSCdSOwHo58j0oaODiYiCXcz3TW2p++De/UHCc10OjSYBRiqTwWhvf61TzsKNJSGlhB9WAY5CPOEokEuwQRlnX3g2zr74BAwN"
    "j+An3/gVcsMlsOMi3pzG8eetwODAENauWQ8posUblssQUoCkBJGEgQ8hq2hMJ8hxHZS1Qdk4KBV9FAsVlkjSju3D2L69F2Af9Y2N"
    "OPvsc1HNMxTHYAIDOAJB1ceU6W1IZxowli8j1Bqkq5S0FrNaWu88WA3jT2fH/nwUDABYtGjJNQlpSOf6lWSjYWEUWyN0yVB5TDQl"
    "qHruuWd2dX/1399ERH0rOjpU7QK8f/3uqm9/+BOf/8GGXf0znFSzCeEIqVxylYKqXYFhgrWEarUKrUMoWE5TQOecedIvz1vYdmtH"
    "R4dY2f78dBQYIBDxvfmxY7fsHHzb+hxndplEeqdNJHaaRGynSTh7kXb2Ii3Xjpbl6n3Dc7b1DF4EQIGIny/PYHF7OxMRd11yesfS"
    "aQ2bZDUvkvGY7e3vx5atO+DEYgitRmACaKuhrYUmUqHjTDGOO2+sXL54za7+rvuZz97GcJmZVnR0qAvnTbm+42Pveu95Jx/xZJMM"
    "BVUKJKy2bITh0JqkJEPFrEyL0F+44JD/ISLd3r5K/MkYpvPAfWkWjsMcalgT1WuCIEAynoQgINQBtIn6KLQllMaLYB3CcRQIGtrP"
    "4rxLzsT5rzkBQ0OjuPLbv8bYcBUilkKsuRFnXHwBYukYegd6kEgKeLEAxowj9McQVsfhV8ZRKY9C+1leNr8Zl55xROWtpy0ZPH5O"
    "Bo7OQ9oQjmUyIUOFAo5WEIGDqS2z4XIM+cE8JFEkRqAZ2i9h5oI5qDAhX9UwMmapXKVG6I2nxnFHLQb6C/sBursNmOlnwO2XvH3s"
    "y088+eSHxnKDLoQHRoBEwsGM6fXr3/yut33so2++6JZfffnDkdUBBl1d/LbPfPcrN9z80AeyFcvxhgb2rJUkBUgRKEr4gMnCIQkT"
    "MshYSLZW53Pi6KUz9376Ted+4QuX/tGJ9DwuOdoNc0Uzh1MtTVXfsUIoIikhlYAkEXUlSEbVaDtUrYpcxZ8CoAlA6c8pCRyIH4hs"
    "rTI+8psNu76y71e3XLWnPE4x18NT6zZg0SFz4SoJkIElglECxAIytB451MoxN1YtVRr37B6a7rdmnEWp2C3MbDsBsQS48bNvOn/0"
    "FzOnvuXWOx56zd7BsRahBcgaUK6A+jgKrzj75M//+8Un3/IxMHV3P/vJOOEyMnPT1x/Z+vbNe/uTsXiztQbCsoENNJRhCCKwtDAK"
    "iGcyCKoBenfvg4CFpBChn8PFb74AK85bht17R/GzH/0auaxFrKEZVV1BPJnA6OAops1swRtedxEEa1SrIcIggA4C+IGBsQQNy44w"
    "tGxGJjxhWuaGRmBrW0PyTXuGc/O3FccshRC6XI6ExVjAra9DU9NU9OwZRDGbh4IBkYSuhmicNgWN02YgW6wgtAJhoYJkuYBFc5pv"
    "JKKRg2LYv7ASTASKgqyPX3Xnmtt+e/W1r9i6Y2eMyNgTjz9230++/LFfRoFuu2ReZTs7AXQRX7du8zEfev9n3lkOyaYbmmFICObI"
    "o7XaRJ6GtAe6p4JyFVaHkNqgIe7h9BUn/yxOtOvF8uKJYcMgYBsKElKRCWsKDSLycCwziCM2DDPH+4G2qHvw+WPVqlWWOjvFyiVz"
    "f/2HudPe1fvUzlOMm7TDg1mxedMOHHvsUlQrBbiOqClEMyQJslbHLQtPxROxYqko+obCU/Yx30NElYOquw8y87oVpx519ZU/vOYV"
    "23fv9YhDamyclz3rFaff+uZjDnvquTJXB8uh/GxD73f+8PDmsyvGY3I8AcuwJkQ85mF4cBQBNOA6qG9tQUNTI4Z69yHf3wPPaoQm"
    "h3Pe8EosP30Ztu8axi+uuA75MQMnnkQQVOFIQn5gGA/dchdiyRjmzp6KufNmIpVK1E4Ti9BEEmeGLFmhUc5pCqZk3KpAjK2VVCpB"
    "VsqkKwxZNAiNATwHLVOnwlUOtjy1HrJiIBwJIyW00Vi05AgYFtBhCIcM+9kBanIC/6hFM39fO/j+7Eb2fCvBB17k7WcvvxvA3RP/"
    "3nLvtfjpVz4OoEMAXYaI0N7eLgBg89adi6oaCcdLsSWXIAXYRjkNWAtrAwirADIw0GAdwIHgsFgRhxw+feDdF51w28cBmmjre6HQ"
    "BGGMJauZmaNWP6sBoRCV1wlgBmkDBIaVfRHcKCLi9lWrBBH51+3s/8qGHftP2F2uSqU8bNq0DYctORRECr7WkFLUeiAEBAsi4UrN"
    "tl7GYvEQ4eIxYCaAbQceXLSACwDuq30dwFWfAN7yZ5rhazqgiV9uHvrGdXdvfNNwNW5lol6wdKOqsycw3N+P/sEeIK5Q39KChrYW"
    "VMsFDOzcAccGqFTGcdZrzsbyU5dj194B/ObH16KY1XBUHGG5Ams1JDFckiBHgYoBdqzfip3rtgKCwMJCKAKRBEQ0B0Q4FnsWTFGl"
    "YvH8Wc2N5bWbdtaP9A3BlkLSPmBCATCjecpUzJoyHT3bdqJv0xbErQMlBUqVPJpmz0WysRljpSqEIEhd5bQuiSUz6+8/HHhygvv1"
    "55bNC5bmi0aAQk58tbe3S2Ym4H+P/DSsBEmPNUlorvXkTqw65ih9ag3IGITVMqzxAa05hhDHLl9yfyOwFgB34oUJSHXXVHZM4Pth"
    "oCHIASwgSEbleEZUMmQBZgHLEYPQRJ8JnS/wnqxqb7cA6OJ5U26b09bwoAwDcoVrBwdH0Nc/BFIeAoNavyrDEEHXmkJ9Fhw4nhca"
    "MzcE6p+ZhGBm6uhggY4OAbRLoF2ivV12dLB4rp2/K3J++Veb93/yxrufeEdWp2y8YRpBeJBSIF2XRKGQR39/D0gS0vV1yDTWIQjK"
    "6Nu7A2Sr8CtjOPL0Y7HslBPQv38Qv/7hr1Ea8RGTHrSugMMAItCwlRDwDdg3sKGBp1zEvDhcJw7XScIRSXgqjbjMIIk6xFCPnb1F"
    "XH3LQ+6Prr29fv3ufmRapgCCYGDgZFKYddghWDBnLoZ27sWOh9dA6qjPOyzlAGkx85B5yPkBKgaoBAEHhQJNcWzp1CMWfHWiTvSy"
    "qEM/c7ZtjUH5zMgZQHdNQ1IShLCCRBRdGkTTW2opMbIGBAbpEBIWplqhmS1JfeJxR15LRKWDlCVe+AkQ+DDGAsKCTTTwgmsanZYA"
    "UeO/cI0upV/k0EAiYkSxQPCN2x+97okd956W9cswJsTu3XswbeZUaEMgQRHrj2zkczPBsACThLHkyGcx9GetY3QDf6r6ffBEnV9u"
    "3P/ROx/e+vERm4BTlybfEAEaqVQcoQmxq3c34Ckk4knUN9Yh1BUMDQ7Cah9al7H4uMNx6itOw9jIGLqv+CXK2QCul0RQLcNQAFgB"
    "mOiw0lYDOho/K0khDEuIJTx2Yh4qviHfhiDDULVaA1lCoAQGC0UWboXq6hvRMnM6fF+joXE2HOFg99btGNrbA2mij6+FhR9UMe/o"
    "o2DiDvLlIoTrQgR5brEFccSiKTcsjzu3g5meb53oZRVnFcKwUASpJEhGMay1NtLLMRwxHq2BNRo2DCCttSKo0pwZrZsvPGRKLYrv"
    "fNGtgNYS2Rp919Teh22NaWkjkVriqDUSTER/wf3oWLWKAeCc0469Ix0TJRNUBHTAe3btRrlcBUPAaoI2BGMtrDawGtCGa3RkFF1g"
    "cOLofpF9GhMBb7x7R+/H/rB60xcGw5gUqUaEZMjYKmJxgm/L2DO4B6EDxJqaUNfWBqsI2fFhsPVhRYh5xyzGSRefh2KxiO7/+glK"
    "gzkoCFQqBViH0DBrLqYtPgLTjzwcM5YtxZSlhyA+rQXwJMrlImZMrcclrzqeTjxuAc2eVYd0WoKpCiNCMGlwEIJ9Ax0IyucD5Msa"
    "sVg9muunoTA4ii1rnsDgnj2QluEQgayGX8lj+iGHIdE6BWOVCrQx8As5FvlhcWiacxceNe9XwAu7eS+rLpBfCgkgCAK01WBSNbfH"
    "RhdZ8wlZRw3ygsFxlzBv9ox7iWgM+NO7P9dy/c+S8aP+K64QzMzde3rTzDU1Zqsj7nhkmYBAzRABZQFrNHPESp2oXdCfyAfg2Qba"
    "TfibSzzsnTm1cf2uzYMnQjk8MjJCuUIRdfVpsA0RsWYjzVBby7wLFmCGM1xA+S9tTWXmht/sGei4+9HN/zxKMWVjSctCCIaBl3Yw"
    "NDaKaiVEpq0BPgzS6QawMRjpHwC7FiDGokMW44zzXoFcqYhbfnY1CiNFxGIZaDDqpk3BlNlz0dI2C048Bitq6n1KQtsAykYdXsfO"
    "bSifdtScp7JB2Lx67dYFt9/7uChYHxqMQAtYFrDaQkgHyo0j7jaAKxJjI6Po37MTxECMJGwYlWXC0MecpUswffFS9IUaiMcBG4JK"
    "WZ4ZD3Hm8iO7m6I+jheEl9UAskMVEYYE1oCxPqAAz43VKr6R/00AuGohrWBrrHSoamfPan4AtRr2/wp+a0Wq5/DvGIC94j3vwfU9"
    "fQ1WB2DJIEO1qbQiEi8g1FJt4EAHVKmUtQuo2uuaPxcHPdMVjP6uQxBR6Ut/eOiudXuGTxwxLvxqHmNjo0g01IFsCGkNQg1I5YJF"
    "RPsgNwYDqg9l2f0LOvQsM8+8cv3eLz2ybe+biokGOKkY67IRxADFE+gfH8L+/ADaprVh5tw2pBtcVKpV9PUMI54iBDEHiw9fihNO"
    "OQmlsQpu+cUq5Ecr8JqmIGCF5mnTMHX6NMS8GAZ270V2bAh+EBW5Yok4kmkPjQ0xnjtnKi1bumD/vIS6LUjE5menT5l+c9lPBoHl"
    "eKqOYsl6xNMNUHEPbtyBJwl+dgy71m1EkB2HFxOAieazhX6IKmvMOfoYtC5ajNGwAul4sKGFDQq2MRwT55146IbDW1M/aSTKdbxA"
    "OZmX1QCYIv0ZyxYCkf8NGxEPOZochwn2O4FgdIh4XTw4ZOERu6P134muZ1pAbeEz80Sz88IxINkIPAXA9YHpQ4CcCeh7i5WFLAjW"
    "mOgUAIG0iSyEACEYmlmEOoRJNDWNAxcOM5eagV0Ais+WCSOioLb4/1eKraMD6OoCjj/xmJ2/+d0DwVCp6gqA+3t6adbcuTAhR8Mr"
    "ZU1h2XKtocNCMJwWpVoB9D3fOsTBlU5mbvnl1t4vPrpu6xuzIs6aGI3N9ZTKMPLlEoYKOQzn+tA4JYF40iJVB5B04fePIZa0UAkX"
    "pxyxHIcduQTZXAk3dP8OxUKAWHMrfN+ibcoMNDU2oTqexe7de5AfGYMggislNCxKVmOELPZRQHvr48iUsnP0iYtfXzZcd9cDTyRG"
    "RvNQSJGyFvVxD45HCIMSCtkChgt5VMZzCCtFKIdA1UgWs+L7IFdh8fHHIT1rNkYCH1Y4ENpA+jkr8n3i3BMX9q44Yt5VjxYK259v"
    "5uevYABRFsYaE2l7EkEKCVublYVax5hFJCDLHM3P0oFGc3Nz5dAlTcmDmYwH7XKcY2761A+6P/eKD3/9FBlLkvS8eseVZI2fhSOU"
    "iscalHQQ87zQqGTrcEUCMUHG1Px9RK1/hEjGBhYAudgxUEr9+A/r/hmFUrsxpqRtWFLMloQSUgpL1mrPicnP3/HY4OK507suWTDt"
    "8Wd2Y3V2dnJXVxemx9zehrhbpmzVBSwqxTJMoGE1wVDUfWtr2kRmIh5iSKPJe5FuT+aXO4a+dP/anW8aRQIldgEWVK6WMH16K1SF"
    "8cTux5CoJ2QaBTIp4qY0wZZLaM4Q4ipBC+YvxOJDD8PYeAW33Xw78oUq0o2tKPkGLVPaUJ+qR2FkCL07tsGWyohLBw5JCGtAbKAZ"
    "YCkhhAcuBbjl5nvcx9etX1yqBtg/OAKmBFj7KJYHUR4bhbUWxhpAa8BaSKGgwABFmvG+7yPd3Ig5RyyB01CPoWwOofJgJSNOoVXZ"
    "feLsw9qGLjntsO8PonT1pXV1I/j7mRMcZYGk5zCRqHWIRUMkDtq5okZwnmieYSZmSiaT+xYA65/NtwfAq0fzCx9+csM/95Q8iLiD"
    "gH04MQ/Juth0LRhBLoQihrA+DKpw0w1weGKhR5kXqu3fhCgecWUCg7kQ2fxYXClnJgsHUkgoawCKOPJCOHBCibqSj7LePY2Zzyei"
    "oYOLdJ2dnQSAFwLbY56TNVyuF8rlMDTENiq86SjlCmsnhucRtGVoY1VVa/EC3J6JxZ++Zlf/5+5es+WtIzZBgXDZkiRFBGN8jGb7"
    "oUWAmbObUC6NoyUtMKXBo5l1AqLASJNE24JFmDV7PnKVEu5/8CFkx7NINzUiKFk0N09BOpHGWO8A8r37IXQ0ucUxYcROFVF3mTUG"
    "bARYMUhbVEKLHRt72BKDpEMMDTZRP4BmC8EunCgpDkDW2mclgqoPL5nG7KUL0ThlKgrWIFvS0FZG7ZwoGF3ul+ccPmPoHRcd/40K"
    "8JNXUmr473JSvFIeCxG1RfL/OtH5wCFPFInISkEwWg8T0ciBnz8DQdl3AzjaiJSwIsUQVljloGIcjtRaHbIkQYoghYIJNSkZbfUk"
    "CGwMDCwES0BayIk5kMqFhcMVVjCsWGgLQbW58wwIViCtuBIGNMU3h64HZgEY6uzEgbbiiRMAQM4ysiTVXJYOKoEPrUNYa0CGEAIQ"
    "bCK30EZsM23YJXpuBYNnxByWmVO/3jH4H3c+tunyQe2J0IkzQ5BQAq4DsPWxZ+8+JBpiWDB3OnQhhUYyPLuxYbBOUSGeTjaJ5kav"
    "bfoMOR6UY4+uWYOBsX4kMimUCgbp5gzSsRjyg4PIDvRCBj5IazAb+IZhOaJoS0RzlAUUEDIsGQgScMkjAwMTMgANBgEiSgFHPmC0"
    "IVkAVih4sSSmz1qIurZpYKEwXLGwiRR8tiCusvILNmOG5SuPW9D3hnOW/WAE+J9XEg13/AUyki+rAbiQeD6pdYoGyDEEI+a55tkq"
    "0AeKa9ZRHGkZCjJgwZbIWMAykTWQLCGEAksLsIZkgjWilrexkU5LbVRRdPOjwhgZAwEmKwSEMSQs10RzCaqmecMQbEKQ1lAhMBvA"
    "ms6D2FYTBktE2XM/819Z6XjQovb6bKAokhPRTFCI4gDLDGMMXGuFNkZNFOK6njvg5b3My3+9p+/9tz62+S19oSesSrGSLpEAlDAI"
    "dRlD4wMgV4AcB8oYXtA2xTZLery5se4+qZxSnMSsVKZhWkGbw7fv2DatrAPEMklUsgHqG1JIOHGM9w4g1z8IV2uw9mGNhR9apOob"
    "UdfQDL9SRmV8BGG1Ah0EIIpU4iQJCEFgjqRfmBQiFrGpdYETICREPAE3nka6dSqa2qaBpEQpDKGDACw9mKqBVKGV1RExPR7Icw+f"
    "f+M/v2LZ11ejvO1iSvY/H77P38wAJqbgcq1XiZ4tqqxNUAQIigRcxwkOakfgg1ubAMARPNUajgifqE2SMQLaiFp2ksASsEQH5MnJ"
    "RJF3lHy10dA6CcCKKDUrBJgsLBlYQTAUpYfAMnKbbDSq0xIQsoWOhtslnuujx7yYEaShSEFCQkHAWhuxLSEQIgTVOujAFsYaISaU"
    "pZ978WMP80n37Or72K0PPv6qMZEWZcTZlR7pWlExDEsYHt6HkMuoa2lEGIRMoaGYxXhzS/M99YnMqgyQG21Mnxjq4MShvj3HMBG8"
    "RIw5X6JUXQJx62G0txelkRxcNgj9CoJyCcYyMm1tqG+eClZxeHWNyDQ2oVosoFQowNgQxoSwYQit/UiFlCPqCUkJx41DOR6cWBrJ"
    "TD28TAMonoCVLnKhhg2jejxJAcGGuTjKyubFkdNk8Lqzjv3R2w6Z/omadM1LIiX/sgbBlVLZcuCDhHtgaITlyAEnS1HDBRi2Nj1d"
    "kYJlrjx3anU0HvpVIWW0mC1FnqQwBkyytrADiFBACQUIEVVeBUCGoxnzskZyJwJLhhUaoYx2fGINxTLquoKFFRJaEAgaAgahDRBY"
    "Nwohnj0FGxmu0RU38nzZaEBbidBE/pTDQMCAsCYKBMnCcGgBzX/O5/eZl1y9ffA/fv/AxleOmBSrRJqlEKTDEpQC4l4MQ0PjIEeh"
    "Id2CWMxBQijEhQsB4rTj7T2T6PHaa/Zf71dnxjylW0QGOaPAM1Mol0PkhvJIp+JItUiUx0oo6kgRpbG+EemGVgSGEIRRPUOJGFQm"
    "jkymNRo6RZGOj4KOtCg4aoiXUkEpCSEdWOVC1O5t1TDCMASRgDUMIRXD+JaLw3JeBnTs/Jan3vu6FZ9f6tA1bwewilm2A/almKPw"
    "sp4ABlHFFbBgEe10E8JMkV4+DgxEft71OyEcFkpoZshaL7IVAsQKzPJAaEE1SRFigKyo/awWfNeugSlqPAfLyNc3Mip0EdeGYkez"
    "gC3LqH7A0fAOEf3+QM3vR9ezqFEYbWtDzmuTYSbkA23EAyIQLBN8RHPD2Dr0px7HQQHvnF9s2//Jm+9de94Y4mycONgwOZLgKAfx"
    "mIN9+/bA2ADJdCzqu1USyZgLJQRAxOTIlg3MU5YAQ6uB2V482SzCcpx8RjwFOLqEUimHMNRwHAdlCqGlgxASbbMWIZWuR2AYpqrh"
    "myoEGWh+WnArmiOrIsFc5UKoKPtHgmAYCBHdAw50tIGJGjWdLUtLTGEIlIZFc0rLo5dkhs86fvEP3n7ojB8Q0RCeFgo2L9UafXld"
    "IGutjRY9RUlPAVhdy35ETszE8Gh6ljD5YEwMk/YD26eUAxtEGRwBhjBONJyOJagmMiVEtNMzDFhzpDcCihTQRPQFIWoTHAXIOFH7"
    "n6BaEIdIWI8ULJzo70AQZAEKoIHx53ZXalW22uKwNSOAsAi0joSoiBCyA6LIGMSz7AIHLf7Wq3YNffnWRzavHLIOGy8BDZDUGpIB"
    "IRR2bduKkdFh1GVSMLqMhHZgtQvFPtKehWrNeIHlZSMCr7/bmHEmeXQhMCfuG8tlekbzGChUqG8sj+HBLHTJQIYSfiFAZbyK1qZp"
    "qEu3wA8J1SBAqezDGJ9NGLIjFaSUPNG8bGFBBqTYojb2DQZROlyRAJHDoXUhBJhtCBOWYP2igNbUmnBx9Pz0/tOOX3Ttm46e99MU"
    "0dp3TPQ1/Bnhgr+1AUzoohy4QGOiHTjK/UcLFlyjQ3MUNApRq4pRrTZgnzuekVaUFJQlS8IygQ0gyUIIHZGzYAGYKA4QMjoVDEcP"
    "oparrp3TtZhAQ5ITHb0KsBwZgRaAo2svxwwmhhQEgQCSdTX1Z6rFrA3VQo5oAdiI+GCZAW2ie0Ii0taEhQETE/4oBui4+25FRJqZ"
    "W7/z2Jaf3Lul71XDgcPGi1EQdZCCjIYQQM+efRga6EU6UwcThpEyhZXQYQgmj+qaW8CJZHqwXDzZlCoLHTdhK75urAjRWiEXg+MF"
    "jBcD6KoGacBBpMlDWmDG1FlIx5tQqhB8JgQ6gCSfqTxAC6c2U75YRHa8BAsHBg6EEwcr1zIc1jqEFajJvBBCo8naqkBoYCikmKPR"
    "GGfMmp4MlsyeO3TUknkPvG1xcycRbb0sKnZMCJ69LFOVXxIDeAY1QCxevLhWNRUsasGvrS1yUYt8J4pRNUWtGiumtkqfA8lUBpKN"
    "EGwNmGGYaWIAHcFCCgGAEFgDJTwylsipzYSsjXhHrQIAWIIRApoNHMEQFDCTYKYaTYMVoAnWMpMANDQjLFO1SKYOKD0XddrqUDw9"
    "kRLQWiNkDSsk4HgImGGtgYAGOLDGhp4lSgDAPffcIwDYrjPO0Mzc9s01m6+6fe3O80ZC1wonIbS2ECCQNUh4Cn09Pegf6Eci4UEb"
    "E0mPQKFS9eEmkph/6KGon9KK4XKR1u/b15KKeS31jQIDQ6PIFkuAqxBP1mNopA9+oQqHFYwGdGCQSbciXdeMaoXhk0RJV+HI0CIY"
    "FSfOTw5d9o5Xfbqnb2jO42vWLx7YP7yg6PtzCuVCzLpJKWOZWvIgGhYupIAjFRQ0UqJaaKxLDc6a0dZ72OI5O5ceNu3JRcDjALZF"
    "zVVMHQzqopde8OwlNYCJWWAf+Nhnj9q2betxt133yys2bdokACCulJ3I8R8IGdkccH8s13zyyFii4RH22Uloi2s692ce3rT9xxm5"
    "N1vKzg7DPLRgKCQhbCza6UNASom4E0dpPA8vlQaLiR4EitwRIBKhFRJaKyjW8BwfqFYooUBkqVa0c6CEU9u1LYQgxFyD+nji7mnA"
    "djD/SbkNayzYEFhEle7QaAQmBBxAGw1LCjEh2PGLSFIgpmS8NXUJb20ts2Fu6+9PLpgy5aTP3//kJ+/dtO/0MZu0Bo4gzZBSQLJF"
    "TEj07e/F/t4BxOJxGI7CFhIC5cBHKpHAUccei6Ypbegfy2HjuqdQLZe4dWobWt0U+nNFjI/lqDCeg+fFEVcJ5MMiwnwFukKoT7ci"
    "Fm9B2Tco+z4CSDgytJTrE6fMT492fvDS9iNduu8gd83bChyyfl1fZmR8aBZYzQkFKwv2pBSB53icydRn6+vqdi+Y4tl5Ub9HCUAw"
    "kdmZqHB3dZHtopd/kLj6Sxd/d3e3+ff/+OySNY8/1d3Y3PAJALyroUEAMErZKAs28WCiu1Tbf8VBAWl0AhgYGGOeqw+BGon2fvV3"
    "D751+satl0jXmQqJeunGSbkepEIoBCwza9dLJ1nElt/60IbGUZtm4QqaaIRhy7C1WoCwDAQlbkm5dNbxR+7WQX4TDFdhje8lUibw"
    "7ZA2YaCYrBeLUTqtikcvmf2T2hyvP52GMzX5ccs1745hrI0yP2EJFtKCtWimCi+bP/2BQ2c3/8syot21heRuAN54xS0PfPKhzf1z"
    "i6LOsvQEROQyko3GLfX19aFvfy9kLA4bpbDAJFCuVpFuSOLo445D05QpGM3m8fDDj2M8O4pEKkZmLA/E0hjOFhCUKrAGGBkahSQF"
    "xRKVQgkxVYeY4yEIKrUMjYFjYamaFcfMzox//J0XX3qkS/d13H236rrnHouuLiYiH8C6F0ccY+oAqDPy8y3+SlB/6eJf9ciGxV/9"
    "j8/cFvdi37zm51d2t7e3S2Sz9nEAXlwa4SpQKGvpHguQE2UJLWqZmMhlUVKiUsihkBt/LjoAA6CPXnzygRZBZlZ/lH6c4OER2XUB"
    "/9t9T275eu+4gQsFosgPnwiAJRFcAfZ9Tc3xZPajpy/5hAv8rub564MaUv50I8wzfjRxDbFMOuUUfJAfEDGgjQF0VMIDhRz3x8U0"
    "ZQsnHbnwm2dNa/xZPdGu2udJ3To2ftmvbrjn39f35du0W2+JpZC1VlKjAwgoDA0NYaB/AI7rgYyAJQGpCIVqEVPnTsFpr1iBxuZm"
    "9I/k8MD9j2EsO46EG0c+W0GoLRw3iaHhcfi5POKOgCtdlPIVpGJ1OHzxMhRzVZSLZVgrwQbwlLBemBXHzUvve//bL3j78rhzd/uq"
    "VbLrjDP0wXWKToAm5pIdlBF/miFT+7Zx40Y+uNeDiLjrBRLZ/nYGUFv8D+4Ljn3vu9/anWlo7r131Y9+SHS1WLx4MW/atKlG8ZgQ"
    "RJ1YlVHe+I+KvDzBy4mOCmv+rPFzR0eH6Nq0idDdbWqTGp+1BLdj/+BOIoLRNhriVkvHRbMKAEsMI0w0GMLYoAxs96Jd7Glj6ugQ"
    "2LSEoifZjvb2qAXyTxjG0w8UzEJKUI0EqI2NAp5KQbRJTfOa0/edeeySzx3n0J0HLaCWX+/a/5Hf33b/+7eNlhO+U2etFkKRhaCw"
    "1sOg0dvXg9xoFo7jAgYRqVAS8pUKZs6fibNeeSaS9UmMjuVx110PITuWQ8zzUC6HgA1h2EDFSyhk80C5AnhxHvcLICOQTLgg6SKR"
    "djA6lkNQ9uEq11bHsvKUI2b0f/ndF76xjeihCV3WZ9kQ+M+Uhw7YRFfXX3u5vwQGUAt4zXUP7D318ve+75cWXnPnl76wkohKq1at"
    "kitXrjTt7e0y6nehWsInki19Zu1oIniNsiwRR0SIP5/mOhBwMz/rL3fecw91nn463do75goGhI16kKm2RCf6kScyVcZoMLOwgFdr"
    "hJlIJ+GPj+NudHc/J7njgOFoY9gyYElCCgVpQ6PComxg3x47a8aX/+nohf9JROUVHR3q3q4uzcxzv/Po+s7f37PmrSM+I5RJG4RS"
    "eFLV7o+BkMBwbx8G+wcQ92KwRgNsIaSLYrWEplktOO2cs+F4MQwOZHHHbfeiXNbwnDjCsg+2NhpwQQSVryLIFyFLRVRFQEQSyUQK"
    "ldEx9IyOQwkJjwlhNY9KYVweM29K4X2XvvLyNqKHVtx9t+o+aOf/R4Z6YRv/KtnVtdJcs27vvK5Pff6qvtH8zDe+4TXfPHt+86Pt"
    "7e1y5TN2BFMbhEcUDYKLNl6uqco9vWIOrJ4ace55g+hZI+ZVq1YxEfFNPSPWWgaHGpbEgZqDlTVfOjI4GGPBbFjVqoscOfcvPAA7"
    "wHBlecFnfpg0NoSy1tbDUnNQlklUdi1ZOPsT7zxi4ap3AnTZj9Y4V7xnecjMsz5xwwNX3fPkttMGQzCrGNhK4UgnGmjHFtKR6Nuz"
    "HyODQ4g5LjiM1h8LiapfQaKlDqefdzZcL4Gh/hHcctPtKJcDpJIZVCsB2GhEvbsWRkqofIBwvIj59UnblEgVJqT0rLGWoIW1bCyx"
    "9tqE37ZwTvaNl1zwreOTznU1naH/E4v/BRnARHZinLnhjNd94GdbekfnHX7I7N4PffD13/32h96AVatW2bd994fHnXLU0aXLTj1+"
    "U+3pqCgfGnF2ouovRZXPiR15og5sOfJxrX3JtM7JkdZqA7YR+5BFFGyTBqyoTUqpcXQYpOtqfv+Lf0M6OA3kKB1YNT6s5i5qwqH1"
    "8WtPPPaYz5xQR5tWrOhQ997bpa94z/Lw1j2jJ73zB90/XNtXODzHnhGuKzUQ8ZiCAMICjiMxMjCA4f7eSH7EGJCMrjuohnBTCZx7"
    "7iuQSdZhcN8A7rjxFhSKVcTjSZT9QlTlJiDUIaAsvIQLP1/htlgMn3zf264/eWrDj0tAJTprYA0gU0A5BgwS0JQBhmvTcqjrrxig"
    "/h0ZQETCYub6c9/1qV/v3D1ySjyR4unTmn85p5a5uCnbP8tT/MEwFV8FYGPtz8REzodqpAeupT75IDr0AcqctbCRzMBLYwChIbY2"
    "0ra0JmpFqw2thq0Nh+OJ62DGX2oAT/vC5ozLPunbkYI4Ynrr/gtPOeo/33HG4p8QUbi4vcO9t7srYOaWL97ywEe//dNfv7e3wOnA"
    "SRuSUrJhiAmKiLGIux6G+/vRu28vYs5EIB+JG/lBBSqVwNnnn4fWxibs27EXd9/6B1QKPhKxBLgYgNnAsIk2HkmQSkEHmh3WNC2V"
    "CA+d2nDlNIrmFvwJ7HlWcuL/hycA/ukz3+18dPWWc6AabFoYffqKk6753dejG7P2qU1vG6sULnEy3q1Pvzod2M4nfBWeWHCMPwp4"
    "BdWqpeal+3BsjDA2kuQT1kbdlBFfF0QWsAJCgCkKPELUVBn+ggf9dDZqbOiJY+bMKf/X9z/1wWlEm/+ppjixqbsr+NljG1996Vf/"
    "u2tzf/7IPKVhVdyCIaEDkHIxwdx2HRfD/QMY2teLJJzIVRMR9973fcTqUnjFha/C1Fkz0Nfbhzt/eyMqRR/JeB1QCkHSgmFgWUM6"
    "DoRyWBCRIAFT8eF5qLQAe5mZ7gHk6Qc5oAcX+DpfBgrCP4wBREEv2a9f+4dzb7vxD+8NZSY0QdVpTace/dcLV2z5YDTSVL39J788"
    "e8iImF8JjmBmSURGWq2FDiFsxKkBRbswMYPYRtyJgyq/BMCwln/hInzaC1GKFAisQ0BI2GiKAUgKkKSaQpuECqrggggRGcFfbHcA"
    "cPTxp33yax95iyGiau2j2b3Mx3z1f2557/d/defbs1WtEK+zhhyyzEJGaqpg30IIAVcqjA+OYLRvCEo4Nb2WqIhYrlRRN7UZZ19y"
    "EVqmT0GhkMVdv7selZEsXC+GoJCHkC6gAG2rEK6C9g2LMKCESoNkaF2yojGdHmwDhmpxz5+cP9yF/7t4PgMymJm9o89806eGsmXP"
    "aW4NyfhI1iVX12T7ACAznM03DlUsj2YLhwKQzGw/9v1uYTkEWx0RzmoMy6hAZJ8OHP+YRPOSuUAxK0LJ2pjQCivJamYSUtWY0BFD"
    "VJqQOTdu92zeN6F495Lg6x99a+nrH33rxH1MXb1x79s++pWffvqJHQOtVVGHWLLOMiCiyToAm0i5zoYM15HIDg4hOzQMVbtOBkGQ"
    "QNkvoWHGVJz/xteirrUZufFx3PKrXyPfPwTpxEFhCDaMMAxg2SKWdFDvAS0JQQklWXmWOGakw8CUOu9+IhqsuW34/xHPaQArV64U"
    "AMybP/KFV2/f03Oq8JosM4uYkli29LDihAhLFpgeGN0yVg1p3+jYLADNRNT3ga/+HIE10GzhHJQMfS43y/JfftJubI8Gwy2YWb8t"
    "LIxlKXSahSJySIJNEBGzKEqNeoJltTCIZH3cvhQxADMTrVwpEI2TjT2UMxd/8KqbLl+9dusp+0ZLgJcykkj4lapgqUBCgIhrfFgD"
    "z3UxOjCA0YFBuNLBxMBB4Tgo+1U0TG3DK1e+DqnGBuTHc7jlN9didGAE8XQGuhpEp6tlkAkQU5JFqUxnnXHC+L++6/yvjvUMPhZz"
    "HTXuV2PaWuEmnce+/yw1jEkDwB9pzTiLT1v5z0UtEUsnWSpBrhIIy7ntE787BrjMlMr5Gtv6hxbcPD7+AWb++Wd/fvMU42tAWrLE"
    "Bzg5OMj1edoFYggSEPSXb8JRpoJpDtGmD33/t99QazZ/uOqPOcpxEZUEGEwghuWY69K0uQv7jjp83keJaAwvUoqRmWlld7eocdXN"
    "VubD/v3nN3/+0Y17L9o9XJYlzSxjjbCAdC0AYhB0RLiDhSABKQSyg8PIDg4hJlXU68AEchSq2sKpy2DFRa9GrLERuUIJN197PbKD"
    "Y6hrbEEY+GDLUdHPGoAJrgM2fkDV8ezeYx35bZo/vYRJPD8DqCkc2E99/5rzB0cLp8FJMZQnWAjSoR+m0y0Hxk+2AiUBFCzJxJaB"
    "ofgNDz389vnnv1I3z55WJ1jAYVHT4oloybWM0tOFsFoGkcERZeClyQExAHzz8td8scz8yx2FkYTjphnwUQoCInjkk1b1qQY+DBgh"
    "ooFalc2+wJVPHZ2dE32phpnTX7ruzve+/6Nf/+iesaBlTLtgJ2nhQDBzNBCE7QH6N+tqpJUpJQpjBWRHxqGYQIhUEkJwVAF2HRx7"
    "9llwG1uQL1Rx5403oTA6jrpMBuQQ3IQLU/LBIUHEPEhIVEtF6HIOwyMDSQDz21et2tgwb57I7tplgeesaE8awESZes1Dj15SNUqI"
    "eL1h5QoQQbqulXHvgLuQBnazNb2Otm1l4Zg7t+2cMmP2lkvnzJs+YOKqFtgxDEe9ueLgKvAzXKBIve0lBSWiHPafi/YFurrs8xmP"
    "dPCO301kuqJEQOwnD22+5NIv/ff7N+3uO6m/JIF4xrLnEkBCsYGulCEdFTXmW665PoAEo5TLITs6BmGjMUKMyO2xzGBX4oiTTkDD"
    "tGmoVALce8vNKI6PIZNJghGgrqkOsaRCtepBB0ClolHN+wiqgA18VIslAUB1r1xpOpj5iuXL7TOLkJMG8Iy8PxAJLi057Q3Hh3AA"
    "FSMrXMCGLJR1yv5YKrqH7QKAP7WpeYR6RzgwjEqmga9ZvXrucXMWzuW6BIKBAAkvBmNr0oTPsvjxjIzQSwiOJN07/yivt6S7mybG"
    "P3V3d+MAr+XPLP5nujrMrK564omz3/2dn/3bxl3DrxisEAp+yvpSkIQjpFCg0IetVjB72jQMDQ9BB1HfAoOgJKGYy6EwNg51oE6i"
    "AceFX/Uh65I49KQT0DhvJoqFIp6490GU8qNoaEwCKkQmk8KUlgzmzJ8JkgLbtu/F4GAeYSmI5ui6HvyyrqI2+KPzb0A4+4czgI6O"
    "TurqAn/sm9fMGB/Nz2IdBxtDkkCWpalYV46Mh+cBuBPHNAgiMh3X335H69bd5+wrVyibHacwpvjGtU/S1NOOR88D61HoHUHMiwNC"
    "gCGixL+dSOwBgqLKJsxLYAT/myPEtYdPS7q7aSXaLVautM9Y2OI9jz8ube+uGUNbdo9c/7GPFQ4+DaJ08AFukGHm1PfvWXvJ6798"
    "xeu37+k9e6RCXsXGODAOhywFhABpjer4GOoSLk459QT09PTB2GhEqLUMB0BhLId8djTq7JoQhZCAH1bgNLfg0BNOQH1zG0ojRay7"
    "/36Ux7Kor09A6BLq6uJobUzi6MMX4aQTlvYalqpUCNuGB3K1VkSK6rphqFFr4JnE8zCACTbn0J5t06oGnmVm0gFJNgA5VAoVNm/d"
    "dxEzf46I8gDQeeErrn1qx94P7t+2Y7pOunaoSoJcB6mUh9bTj0Rl535kN+2CzVXgSCdqnBZqolcLhi2s1gCTZGZxcFbi2fzUZ6o3"
    "d3Z20oR0ShfRn+JT8EF/n9gMzHi8v189senx1Edvu3bmaG9f2VHucHNT08jTmwGLri46QMBj5hlfvfEPZ1786W9dvrMve9xQKURV"
    "JuCza42BcMDkKSAISsgNj+Koww/DaStOxkOPPI6du3uhnBiMiRpyivkcStlsRNajSMMUAggsw2tuwpxjjoaTqEdxpICtqx9BeaQP"
    "8ZQHUy3AkIDHHlKOAyUlEFgZVgORH6+gWgphNEBwYZkhpeVJj+cFGMDQ0FDUgF4pHUJMEkTaMitrGSRZCCHs4NDY/C/99+0XAvhF"
    "R0eHIqLdq/b0fmfPlT//8trRLNxprTYEiQIstMtoOHwWps1tQ7hvDIWBUVSzeZiKD/ajAXm1dnOQkP87CxNNpTk4QMGzZGp4QqKN"
    "mR08rfVPAJwc4OxAMH1fbuzQkaGB6d9+8v4F5WIR/f2FHm11FjGxYca8mZu+fcYl40BE/Jvw7wFgkHnBf//+/n965Se+/fodu/bM"
    "GykbGCdlEUtx1QhhSQohGJDEpewAJSnApW9ZaRuaW8Vvr78VwyN5KC+BIGDEFFDO5VDJ5RF1Q1BE0xBAEGrE2tow9/DlMPBQGB3B"
    "vrVPws+OwXMVrF9FaAQEuSiXQxRLIXbu6kMuW50yng+wa+cAqkXDxgckFAuKsXJidnKpvwADuPfeexkARrOV1sAPABWjiaZ2lgyp"
    "HIwWCuLeBx56HzN3E1HY0dEh2mdP+0H/xecv+vH1N79z2+AgREPGUF1aBBI0aMpwEhLpI6Ygc8R01JUC2LEygsFxlIaz0PkyUC6g"
    "Zc4R85n5aAA7aou38GxpSWZOIpqQLgF4Q8C8USBTABL3lMvTx4r5mSO5kabxYilV9CtTq36lUVf9NhmEUjBtF5IeUU7skQULFz5x"
    "zlFH9Rz2dFFPALDd3SsNM9P163cdfv1tf3jbyg98/s27B3Kto2UDDY+lm2QIV+iKhRIEEgGzrlK1OE7HH3mIvvR1F9knN+xSP77i"
    "KsBNgYQLHTIcIVHJFaLFby3IRq4KCYFAh3AbGjFj0RKERkEXSti//gnofBYx5YADP1JWYwmJGLTPGBspI9BjGBkzGBgc5/69veAg"
    "pLBSBapVwaGmVCzh4s808U8awB9hBQH3Yl/PrgFFFmQMgwzC0IfnKATaCJDDj63bdMKHv/qrjwPo6tq0SXYRFZn5Q+l4fOdvbrzx"
    "8vUjw9OHyiXIpgaLZAKhDWjM5ImNRbIuhXhLI1KL2lBnGFwORHVvL8qzWhd9/JGHfqOrhb2pWLIqgfHPPXR/jqIJqghNSBbkdDx0"
    "X0sQ6LixYdxCpDS4MdBhqlSpyEK5pMIgSFolACmRjMdQ77hojMW3T2mdendTXf1vFs8/5JHlRM82kMIWmad+/vu/Ovl1//Htd23b"
    "u/+0XMXGcz5gZcLCcUEWIgiZEAaICViUC4J1mVoy/6+9c4/yq6ru+Hefc+79Pec9k2TyGPIiJCGS8CYYCOGhFIFSZEApllojrS+s"
    "ii5ty0oQRUFQFoooQu1C2qojtSCgYAIkSAzP8kokIQl5T2ZC5j2/3+/ee87Z/ePc3zwoobTFluL5/JOsNZOV+d05+56z99n7+83x"
    "xR+/aN+M6bPC2394V/2Gl3eITG0TIg0QW4SCoEtllPp6QekchLGu2hPbBEFtHSbPXQArA0RD/eh6eQPi3m5klHJt0TCAsAgzIUIZ"
    "Ii5pWJShrYQMLAa7OqmtyAiNhc3CUiK1rK/pnTah+VYAMdyIht8NxpYIX3f5L12q1qxZo8++8K+Wr3tq8w/6bcEYklJlswhyObAM"
    "YGAYlUG0tRTNF6/45OUfPeuoW6pjkgCwk3nBbQ8//KX1Gzee/fLgQG03WyQZBZuBJSWhCZAqJBWECIMMCRbIaAk7PAhKSsgHCgEY"
    "OZVBRkonm02psws5KRElBMhYMDnPMWiNAISiDJAjifqa2srk5pbtUxoaV0+Z1PrIMfVNj08B9hxkR1F3PfXi8Q8++tTFv3tp25mv"
    "9g7O7NEBYgQwLK1mScSCrEkg2IKIrY7LgqIhtDbksXjx0ZuXL79469pHH5v1ne/9ZHZfnBW5Yi0SFgiCDAKSSIZLKA8OOI0irrZo"
    "CxgGRC6LGXPngoo1KJdK6Nq6GXH/qwjIugF+CgGOoSQQ5gugTAgRBBDZDHLFIg/2HaAT5k6Orvzsh68fKvf+WiWJzqgsz5tQu7vx"
    "zZSB/Q4wyoQJE1wrweFHbFr/7FZtS7GiMAPYxF20kICVgqhQwzv3D6gbvnnz9Tfd9ai9/P0nfR8AXXbZ91Ub0YvMfMmWZcuOvPvZ"
    "Zy7YsG37+Zv27D10RzwsylECmw1gYKBNBB0lVgqFQW2hBEBBwEYKzgQhIhKQLJhhyZhEsrWUURJZAjJMaMkXoWwcC5NUGhrry0UZ"
    "bK6vq980vbVtc9uUyfuOCXPPFoGNr6cmxsyZ+zbuXrTq4bWnnXPF19/X1Tt09P4hnekb1pCqwBrSagNBLIUztdOQ0FZzRGFcEVPz"
    "EkcvPvLZDy2/6P4jpjVGX/rq7R+46561c1ShAdlcHtYwJCyUNYjLw4iGSqnSXNruLKVTcggDTDn0UMh8DuXyAPZtfRnJQD9IKpjU"
    "0E9CO10iKWC0gbEVCGMBbaBjyzqOKGOjLYuLuIZqGkuv86Jjv9zf5A5QbYJ7ZYgnnXHKn6zftmfgEIQFCymEDCTCfBGcLSKxFpI1"
    "o9xPk+qD+IzTlq68dcVl1455w8rq2ZOZJz7Y3b/wuZ1b379rX9fhnX09Ld2lgdrE2qZYiaAURdCw4FQsVykFFSiEQqGYySMLQBKX"
    "CzW5Uk0uV2rI5vom1TVsby3WPVlUcpOF3Xz4lOmDhwJdRDR0kM8lAbTc+fjvjv7t+ueP2/Lylvfu7Txw+LA2xQoUYlLQHBipcqRj"
    "I9hoEElYJqdUYMvCJv3U0pTHUbNnrrvgvPeuPu/YmVt/tfnAvG98+RuXPL9595RMcSKzypJxvqyQUiKpxCgNlaHISTAaxYBQsCwQ"
    "FmvROmMGgnwW5SRG144tiPt7oKQAa4KxBCkYCglCId0sMxMgBUgpWEGQUtm4UhJLF0z57QM3fGZZR0eHBtKeKCfd6I89/5UAGLt4"
    "Tzp7+Y3PvPDKpyOqM0xCgochCzmoXANIZpEYAwnLpIcppwxmt7U8tOzkY2742qf/bO2YhTgyY5tWaEIAwS5g6qbu7sN29vU0JSZp"
    "S9g2a2tDkqSYBAkLG0gVKRKdtZncrkkNDd3Tamt7ZgKvwFkYmYMt9rE8289zHl776GnPb9i0eOfu7hP2dffOPtAfUTkygFKwRBZB"
    "ABaKnKGNBDsfYSZSVuuKDBCjKWvxrjlTH3/P0mO/96lzT17XByy45gd3f/Tn9zx05s7uQWSztSxJEpPr35FSoFIqo1IuOz2uVCSL"
    "pYARAYKaekyaPgvZQh5xXEHXnl2oDPZCEiBSR0untSlATCzJtcxRKiYMOLslUsrYaFAef+jEh1Z/7+/O+ENvb3hLAqC9/aeyo+NC"
    "c/PPV5/4tSuvXdM1QMKKDEESQRKEChHkipCZLJLEQJBlQZaRlERD3mLq1EnPHDZ79h3nnPtHq88/dtYGenPtBSINlqp5UdWX6011"
    "aaZ3A9l7N++e88LTm+dv2bb1pC1bds0aiPRxfYND9YPlGOXEwkIhCPJGSEGgMsXWkkUAYwhSBhBOYMeCWOYCQmMY67kzpj689IRF"
    "t11x4ak/IyJ7y73r//gXq9Z864lnNsyocA4iKLI2TJS2OISBRBTFqJTLTq2OR9s/NBhhbQOaW6ciU6xBYjQO7N+HymAfFDByicXs"
    "noaSgm1UIWsYUiinCifcPANJAZkJLZe7xYKpxbsf+8dvneePPG/NDgCkdqFnXvK529Y89tSHKWy0laQ63c5Q2SxEJgNLyt3uMiAl"
    "WeKYOKlQQTGa6zIDjQ11z01rm/x0S+OEx05cPK/zT5ctfhFACW4I3bzJwKgKSVeDJPPgS1tnv7R5b8tT659rtDJZ0rV/YNarPb3N"
    "kea55YTyQ5FBpA1YSRhjGUIxSQlrmSRJ0omGMZHz7UbAgVDMSULEmgLJmH1IU9+JixfdvWj+YT9afurC1QDw6KbyzGuv/cpnXty+"
    "56P7yyKTydfYyCqRGIIUBGINyQyTxIijyLU7p+uxqg+Ura9DbVMzVCaLRBv09LwKoytOQiCxTpCXFChQYFNGXmjUZ6WB1rGwbn6a"
    "wc7XQBCgAhHYgUprQ/7KNT+++ds+AN6iAKjmAutf5amXnnPeg9t29M4LaifbijbCCqfOSkoAMoBUGWTCnJP9Y4tACssmBptIKBhI"
    "YuQzCrVZacFqcyFf09PSVGfravM9pUg/V99QJ2pq8o2l4aG+oaGov2ViY3OYzxYSHQeVcrlmaGi4YXgoyvX3D6qBwWEZx3GNyoZt"
    "kebCYDmBhkJi3NnasIAGMYvAkrDISC0siBJt3PnZ2tQsm9kmggWDhYml1AkaawJMaK7dfdRxi1Z96JLzvntKW/2T6bNo/Isrb/zY"
    "+mc2X77nQHkCh3mQDK22JEASlhnEBqEk6DhCXK5ASNfa4G5jBXSioTIhapuakcm642P/QB/iqIxAkFNuIAVQACtDkLCcpQp96rL2"
    "xxcvOGzlzu2d+wsUUJIkcMGrCQGgIWWM8lBzI7Z8eNmyil/Wb90OMCJ8e/PPfrPsm1+55t6dXeW8bJhsIjbSaeunyZ5SUDKEVNLJ"
    "jI/IkLBT6CcLskaQYQpV4DRCrdPb5NQwW4IhlYQSCtZoGGYwORXnJLEw7JQchAoAGSA2BBaSSaQt/iSQDvA7W4CqJiMsksTAGnaC"
    "vWyZ2LBNKhKVEkI2mNRSP3zozGmPL1583E//cvn7Hmgl2p4u/Pq//X7Hn//6wUcu27q7Z14ia8BhjWG2AgARhFOaIEARIYnK0FHs"
    "jjCCRt7+idEIwwzq6usgMyGM1hgYGIBOYgTKuXYTAYYkQAFIKta6RLMnF/iW71xz7rIJ2Xv9cv0/CICxQfDl7/7s4jtu+4fbd/To"
    "LAr1GsZIw5bY+Ry55SAlVBCAhATLAEJI57Xl3AFAECxJuEYeJnb+UcIZh4YqdVepekwJJFaDUzkVWMvWGqoabFhIYpLOu53Gqky4"
    "1uvUiBVGW4YhFkxMNpbCxggpQYbjqG1S/TPzFy5Y3X7JB+4/Z97Ef0tneMHMDVf/6IHL7r37/g9s27FnUckocKbGCJURxoKklEht"
    "N8AAFEkkcYy4UoGUsqqqBRKAthZSStTU1iLMhEhMgsGBflitEcjUKE84D3D3kCSIBOtkiOZMqzVXX/PZk567c/rjOAUCjxxMOWkl"
    "rrrqKvZHn99DAIyt5Fz/w3tO++5td36ns6cy1ySWVViwibHSUNV3y0BICZISkApKKggCFBknjhKEkNIlcmxR1eSBVAqJEiPlJ8mp"
    "rDoAzTb1FHZ5sUhFZ22601hD6ZxvWhlx6g9sGdbahCQnwsQRckqgPiNta1Pt5kOmTnzgyIUL7/zbj5z17Ngkm5kLK/7+vnPXrFr9"
    "6U3b9x1/YKgMlS0yoJhlIFgoSCnBxl3EMZyGj040tDFQaS//SAAAEIFCvlhIdYMsSsMD0LF787NNJ+OqKQ5plzATMcdlmtIU2qu/"
    "8eVllyxsW/t6coSe/70AANrbJTo6zJrdpWlXfeHz17/0wqYL+0sSicjBqoyxBAE2VG07ETKAtc6fS6SOKKRCSBVCSjkyBQZykt46"
    "FcoVqX3SiHwoOUlxozVYW8iqjmj6EZgEM4iFcMP21hpXJCGBQgg0FOxw2/QpW1pbmx48euHCe694/6nPEVH/2I9WYp72Nzfdcd4T"
    "T7146fad+47u7a/ABDkWQYaN0UKkRzoBtzNZ4xSuBZEzfTZ6JE+3YJAQ4NQXK5vPQSoJYwziKIKJSwd98Jqdny4xWJdL1Nqg9A3f"
    "vm7pB4+avi5VZfM1/d/3TfBB6egw7e3tcunU/C4AF33xutt/sHbtb/96x56us17tfVW6ZmDBpNzUq5TsvKh11afamc2xsdBEqWlG"
    "alcEATPi5I7qjCTSFykMBMOSq4C4shCDXCUk0RVJAmR0hFxIaCiGaGpu7GxtbX1uzpxZ65cuOeL+8489bAcRdf8YwOfHVJd++ULX"
    "gn+640cXvfu85R/cva93xmAkoCE5zNYwIISxlgSJNNRcVFqbCk1ZA2Ps67jauO9XUkAoATYGiTGIdQKTJG8sPWGrcvLVOQlAqsQf"
    "a94WAQCgw6kdEBHh61/4yCoAq66+peOURx5ae+kr2145va+vNHUoSaRlIKkwZJhlScqQdNc4MJaq1rlId4XUQye1zKgGCqr6cbCW"
    "GTaRAkzEFoItKTJgWBBZNNbkzYQJzdvbDpm8Z2Jzw7qFC+a9cNZZS34zM4fdRGRvek1Jdf3+aFbHHT9e+u7zP3lqZ2/5nAMDpWLC"
    "DFYFy5kAkpQwI4qmdmTpV3X+UW1kM3Y0GMbIighiKBWCnPkbTBK7Y1xqEfVG+y6n1q6cevQ5/zD2AfB2CYB0gbI7EbXLjo4Oe+XH"
    "2h8B8MjGfm667qs3HrNj+/Zzdu/tXFgZHDpqOKrkrSUVR6nlqCawlO74ICRIBKmmrIRlTc7tXaQLyYnYhmEG0lSQC0VcW8zFHMfb"
    "RJjdNW3KhJ7auronTznzPVs/cfYxLwLYWz3Pf2r85Vjbvzy/o+m+f73v1FMu+fypnd09x3V19TWVjQDCAkRQY0BEmq0Qwh1VyDKk"
    "SvVMnYSEO6pV8w9rYK0eeeNbtiPGx1IGkAJgNmDLLpFPh16EEG+cpvKY+GB+64SKPG9BDnDQ1MAFAsZPXIU/vP/5w9atufcwY3D8"
    "xt9tK+7r7so3Nta2kRR1gQxbdWxV4taocOd+0yuJ+i1EvzXoy9XU9U2fOcPmC0GngHziiIVHdi+a29p30rwpO6vVmoPx4gDPv+O2"
    "jvnb925b0tl54PQ9u/bOHCzr3FDFILYKFBRYhBkrhBXVSpbTKzVpAs6phGLqZ5zai7kcw4LYjhsfttUSLQkIKcGQI0KJpnpESitl"
    "NH5HGvdzG83OSZMt6/IQzWrN6WtuvG5J+6Jpj1etg/yyfZsFwNiLswsvvFB0dHQAbzCAkd7sTuwEQgZ4EJB1AE9y3rvRf6eXhZlr"
    "/vnRF2asf+LZE7Zs3nrynr1dp+8/0DtxcDhCZASIBJQKLUMxkxRWCLJpmXJUwNQNaArr2hGsGLVudWomo34GBDtODNoYAyllmtwT"
    "rH3Ni16MqmPzmMc+PgAIRgOwGgKWk+EBHDq1ULn9J7eevKSl8JRPgt/mAfDaw+yKlStp48aNlAYEj6Z5/+NAk/es72p+bN09MzZs"
    "2PKu/v7hoyFzS7v3H5g4HEUNwxWNUpRAqNAKmWErFMDWqZCkbQQsqn+GqWF26lvMoyVYQ3rEvVgwRvT/3R2GGVdyr+YBVVPAEdFp"
    "Gv16NQjcwSa9QxgnA5MaccOCjDZxqV8tW3LEk7++7aplRDT8hp5knrdZAPwn/y8zY+XKlZT6RI2KSBNh3c6d2cXTpqmbfvnYhIfu"
    "eyjf0pA5REhx3KZNuwqDfb2HJFEy/8BApQ4kWuPEEsssRFCAMc6EW7tLgRHVczvivpq+e2nkuA0zxqt+NAF3C9lYZxRcNdbAOCFf"
    "PqjQI5MY9QqgkbgZqfezkBhp1xm3ARCgGUllCIgGcfictp7Pffbyiy494/BVfvG/swJgXP7Q3t6ei6JIPL834l/94ueqmMl9UJvk"
    "gv7B4TnDpeE6CFm0hlGJNIMESCoIGVrNlEgZmDCbYWuZjTGCjSauXogZ43JKQamXMMYtYgZBiIDGPg1KPc3SIBBCCELqEz/6tnYX"
    "WmO97a1ljFFHJytHo2y87qyACFT1nxLATHb0OCSUSmoLGZo+bfLTH//4J754wYnTHwNWCMD39L8jAwDMdNmtt6reVatowwYgl2vg"
    "p5++v6YwcdrkmdMnZt515PwJxZpCZqCfd7NRw/n6HA0PxyIq9yoEgNEQtXV521DTYpIkhhGGkgSwxlCcxGBrCGxlggQBAiRIQEKM"
    "rNzAZkYLLQGQEVkeU85UVgoSIr2uTUaLZkEwvoZGBGGtIWMkK2mkEGONPtS4v4Zh0ZCUzMaQkZYVAmgkSMrGTpneVlly8onm9JkN"
    "24ho+DUm5B7PHw4rXisH43kH7gAH/7kIK1agPRXpmj9/Pl8FYAX+o2HDinfcr2UlVq5857qyeDwej8fj8Xg8Ho/H4/F4PB6Px+Px"
    "eDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H"
    "4/F4PB6Px+PxeDwej8fj8fw/5d8BI4H0yDCjTocAAAAASUVORK5CYII="
)
LOGO_IMAGE = None
LOGO_FULL_IMAGE = None
try:
    from PIL import Image

    if LOGO_PATH.exists():
        LOGO_IMAGE = Image.open(LOGO_PATH)
    else:
        LOGO_IMAGE = Image.open(BytesIO(base64.b64decode(_EMBEDDED_LOGO_B64))).convert("RGBA")
    if LOGO_FULL_PATH.exists():
        LOGO_FULL_IMAGE = Image.open(LOGO_FULL_PATH)
except Exception:  # noqa: BLE001
    pass

st.set_page_config(page_title="ClinKey", page_icon=LOGO_IMAGE, layout="wide")

# base64-encoded logo for centered HTML rendering
_logo_b64 = _EMBEDDED_LOGO_B64
if LOGO_PATH.exists():
    try:
        _logo_b64 = base64.b64encode(LOGO_PATH.read_bytes()).decode("utf-8")
    except Exception:  # noqa: BLE001
        _logo_b64 = _EMBEDDED_LOGO_B64

# ---------------------------------------------------------------- session state
SS = st.session_state


def _defaults() -> None:
    SS.setdefault("dark_mode", False)
    SS.setdefault("messages", [])
    SS.setdefault("session_id", "")
    SS.setdefault("search", "")
    if "pipeline" not in SS:
        try:
            SS.pipeline = ClinKeyPipeline()
        except EmbeddingConfigError as exc:
            st.error(
                "ClinKey could not start because no embedding model is "
                f"available and demo fallback is disabled: {exc}"
            )
            st.stop()
    SS.setdefault("pending_question", "")


# ---------------------------------------------------------------- helpers


def confidence_color(conf: str) -> str:
    return {
        "HIGH": "#0E7A52" if not SS.dark_mode else "#4BD79A",
        "MEDIUM": "#B05A00" if not SS.dark_mode else "#F0A64B",
        "LOW": "#B05A00" if not SS.dark_mode else "#F0A64B",
    }.get(conf, "#8A99A8")


def chip(text: str, color: str) -> str:
    return (
        f'<span class="ck-chip" style="color:{color};border-color:{color}80;">'
        f"{html.escape(text)}</span>"
    )


def _messages_from_session(session) -> list[dict]:
    msgs = []
    for m in session.messages:
        if m.role == "user":
            msgs.append({
                "role": "user",
                "original_text": m.original_text,
                "detected_language": m.detected_language,
                "canonical_english": m.canonical_english_text,
                "language_name": m.detected_language,
            })
        else:
            msgs.append({
                "role": "assistant",
                "localized_answer": m.localized_answer,
                "english_answer": m.english_answer,
                "target_language": m.target_language,
                "citations": m.citations,
                "confidence": m.confidence,
                "safety": m.safety_classification,
                "evidence": [],
                "canonical_english": m.canonical_english_text,
                "detected_language": m.detected_language,
                "language_name": m.target_language,
                "providers": {},
                "elapsed_ms": 0,
                "topics": m.topics,
                "intents": m.intents,
            })
    return msgs


# Example prompts for the welcome screen (aligned with the bundled evidence)
_EXAMPLES = [
    "Explain the symptoms of type 2 diabetes",
    "What are the symptoms of hypertension?",
    "How can I prevent heart disease?",
    "What are the risk factors for diabetes?",
]


# Human-readable labels for topic/intent keys (used for chat-history titles).
_TOPIC_LABELS = {
    "hypertension": "Hypertension",
    "diabetes": "Diabetes",
    "cardiovascular": "Heart & cardiovascular health",
    "cancer": "Cancer",
    "obesity": "Obesity",
    "vaccination": "Vaccination",
    "tobacco": "Smoking & tobacco",
    "lifestyle": "Diet & lifestyle",
    "medication": "Medications",
    "infectious_disease": "Infectious diseases",
    "anemia": "Anemia",
    "asthma": "Asthma",
    "respiratory": "Respiratory health",
    "neurology": "Neurological conditions",
    "mental_health": "Mental health",
}

_INTENT_LABELS = {
    "symptoms": "symptoms",
    "causes": "causes",
    "complications": "complications",
    "treatment": "treatment",
    "diagnosis": "diagnosis",
    "prevention": "prevention",
    "risk": "risk factors",
    "definition": "",
    "comparison": "comparison",
    "side_effects": "side effects",
    "dosage": "dosage",
}


def _main_idea_title(messages: list) -> str:
    """Derive a short title from the WHOLE conversation's main topic(s),
    rather than just the first question."""
    topic_counts: dict[str, int] = {}
    intent_counts: dict[str, int] = {}
    first_question = ""
    for m in messages:
        if m["role"] == "user" and not first_question:
            first_question = m["original_text"]
        for t in (m.get("topics") or []):
            topic_counts[t] = topic_counts.get(t, 0) + 1
        for i in (m.get("intents") or []):
            intent_counts[i] = intent_counts.get(i, 0) + 1

    if topic_counts:
        main_topic = max(topic_counts, key=lambda k: (topic_counts[k], k))
        label = _TOPIC_LABELS.get(main_topic, main_topic.replace("_", " ").title())
        # If the whole chat is about ONE topic with ONE clear intent, note it
        # (e.g. "Diabetes: risk factors"). Mixed-topic or mixed-intent chats
        # just show the main topic.
        if len(topic_counts) == 1 and len(intent_counts) == 1:
            main_intent = next(iter(intent_counts))
            ilabel = _INTENT_LABELS.get(main_intent, "")
            if ilabel:
                label = f"{label}: {ilabel}"
        return label

    if first_question:
        t = first_question.strip().replace("\n", " ")
        return (t[:40] + "…") if len(t) > 40 else t
    return "New conversation"


def _conversation_title() -> str:
    return _main_idea_title(SS.messages)


def _render_welcome() -> None:
    """Centered hero + clickable example prompts (shown when no conversation)."""
    # Logo centered in the middle, directly above the "Clinkey" wordmark.
    if LOGO_IMAGE is not None:
        st.markdown(
            f'<div class="ck-logo-wrap">'
            f'<img src="data:image/png;base64,{_logo_b64}" '
            f'alt="Clinkey" style="width:96px;height:auto;" />'
            f"</div>",
            unsafe_allow_html=True,
        )
    st.markdown('<div class="ck-welcome-title">Clinkey</div>', unsafe_allow_html=True)
    st.markdown('<div class="ck-welcome-sub">Your AI Medical Assistant</div>', unsafe_allow_html=True)

    st.markdown('<div class="ck-examples-label">Try an example</div>', unsafe_allow_html=True)
    for i in range(0, len(_EXAMPLES), 2):
        row = _EXAMPLES[i : i + 2]
        cols = st.columns(len(row))
        for j, q in enumerate(row):
            with cols[j]:
                if st.button(q, key=f"ex_{i + j}", use_container_width=True):
                    SS.pending_question = q
                    st.rerun()


def _render_evidence(evidence: list[dict]) -> None:
    for e in evidence:
        st.markdown(
            f"<div style='font-size:.82rem;padding:.35rem 0;border-bottom:1px solid "
            f"{'#1E3A4E' if SS.dark_mode else '#D6E6F0'};'>"
            f"<b>{html.escape(e['organization'])}</b> — {html.escape(e['document'])}"
            f"<span style='opacity:.6'> · §{html.escape(e['section'] or '—')} · p.{e['page']}</span><br>"
            f"<span style='opacity:.6;font-size:.72rem'>{html.escape(e['chunk_id'])} · "
            f"sem {e['semantic_score']:.2f} · bm25 {e['bm25_score']:.2f} · "
            f"rerank {e['rerank_score']:.2f}</span><br>"
            f"{html.escape(e['excerpt'][:320])}"
            f"</div>",
            unsafe_allow_html=True,
        )


def _render_citations(citations: list[dict]) -> None:
    for c in citations:
        st.markdown(
            f"<span style='font-size:.8rem'><b class='ck-cite'>[{c['number']}]</b> "
            f"{html.escape(c['organization'])} — {html.escape(c['document'])}"
            f"<span style='opacity:.6'> · §{html.escape(c['section'] or '—')} · p.{c['page']} · "
            f"{html.escape(c['chunk_id'])}</span></span>",
            unsafe_allow_html=True,
        )


def _persist(m: dict, role: str) -> None:
    """Mirror a rendered message into the (per-user) history repository."""
    msg = Message(role=role)
    if role == "user":
        msg.original_text = m["original_text"]
        msg.detected_language = m.get("detected_language", "")
        msg.canonical_english_text = m.get("canonical_english", "")
    else:
        msg.original_text = m.get("canonical_english", "")
        msg.detected_language = m.get("detected_language", "")
        msg.canonical_english_text = m.get("canonical_english", "")
        msg.english_answer = m.get("english_answer", "")
        msg.localized_answer = m.get("localized_answer", "")
        msg.target_language = m.get("target_language", "")
        msg.citations = m.get("citations", [])
        msg.confidence = m.get("confidence", "")
        msg.safety_classification = m.get("safety", "")
        msg.topics = m.get("topics", [])
        msg.intents = m.get("intents", [])
    repo.add_message(SS.session_id, msg)


def _previous_user_query() -> str:
    """Return the previous user message (for follow-up context resolution)."""
    for m in reversed(SS.messages):
        if m["role"] == "user":
            return m["original_text"]
    return ""


def _process_question(question: str) -> None:
    """Run a question through the pipeline, render the answer, and persist."""
    context = _previous_user_query()
    SS.messages.append({"role": "user", "original_text": question})
    _persist(SS.messages[-1], "user")

    with st.chat_message("assistant", avatar=LOGO_IMAGE if LOGO_IMAGE is not None else None):
        with st.spinner("Retrieving evidence and grounding the answer…"):
            result = pipeline.process(question, session_id=SS.session_id, context_query=context)

        st.markdown(result.localized_answer or result.english_answer or "*No answer produced.*")

        badges = []
        if result.confidence:
            badges.append(chip(f"Confidence: {result.confidence}", confidence_color(result.confidence)))
        if result.safety_classification and result.safety_classification != "ALLOWED":
            badges.append(chip(f"Safety: {result.safety_classification}", "#B05A00"))
        if result.detected_language != "en":
            badges.append(chip(f"Language: {result.detected_language}", "#0060A0"))
        if result.error:
            badges.append(chip("Partial error", "#B3261E"))
        if badges:
            st.markdown("".join(badges), unsafe_allow_html=True)

        if result.citations:
            with st.expander(f"References ({len(result.citations)})"):
                _render_citations(result.citations)

        if result.evidence:
            with st.expander(f"Evidence panel ({len(result.evidence)} chunks)"):
                _render_evidence(result.evidence)

        st.markdown(
            f"<div class='ck-disclaimer'>{html.escape(settings.app_disclaimer)}</div>",
            unsafe_allow_html=True,
        )

    SS.messages.append({
        "role": "assistant",
        "localized_answer": result.localized_answer or result.english_answer,
        "english_answer": result.english_answer,
        "target_language": result.target_language,
        "citations": result.citations,
        "confidence": result.confidence,
        "safety": result.safety_classification,
        "evidence": result.evidence,
        "canonical_english": result.canonical_english_query,
        "detected_language": result.detected_language,
        "language_name": result.language_name,
        "providers": result.providers,
        "elapsed_ms": result.elapsed_ms,
        "topics": result.topics,
        "intents": result.intents,
    })
    _persist(SS.messages[-1], "assistant")
    # Update the chat title to reflect the whole conversation's main idea
    # (not just the first question).
    repo.rename_session(SS.session_id, _main_idea_title(SS.messages))
    st.rerun()


def _date_label(ts: str) -> str:
    try:
        dt = datetime.datetime.strptime(ts, "%Y-%m-%dT%H:%M:%SZ")
        now = datetime.datetime.now(datetime.UTC)
        today = now.date()
        d = dt.date()
        if d == today:
            return "Today"
        if d == today - datetime.timedelta(days=1):
            return "Yesterday"
        return dt.strftime("%d %b %Y")
    except Exception:  # noqa: BLE001
        return "Earlier"


def _group_sessions(sessions: list) -> OrderedDict:
    groups: OrderedDict = OrderedDict()
    for s in sessions:
        label = _date_label(s.created_at)
        groups.setdefault(label, []).append(s)
    return groups


# ---------------------------------------------------------------- init
_defaults()
pipeline: ClinKeyPipeline = SS.pipeline
repo = HistoryRepository()

# ---------------------------------------------------------------- theme
st.markdown(inject_theme_css(SS.dark_mode), unsafe_allow_html=True)


# ---------------------------------------------------------------- sidebar
with st.sidebar:
    hdr_cols = st.columns([0.9, 2.4], gap="small", vertical_alignment="center")
    with hdr_cols[0]:
        if LOGO_IMAGE is not None:
            st.image(LOGO_IMAGE, use_container_width=True)
    with hdr_cols[1]:
        st.markdown(
            "<div style='font-size:1.5rem;font-weight:700;line-height:1.15;'>ClinKey</div>"
            "<div style='opacity:.6;font-size:.8rem;'>Medical Evidence RAG</div>",
            unsafe_allow_html=True,
        )

    st.markdown("---")

    if st.button("+ New Chat", type="primary", use_container_width=True):
        SS.session_id = uuid.uuid4().hex[:12]
        SS.messages = []
        SS.search = ""
        st.rerun()

    # search
    SS.search = st.text_input("Search", value=SS.search, placeholder="Search chats",
                              label_visibility="collapsed")

    # date-grouped history
    sessions = repo.search(SS.search) if SS.search else repo.list_sessions()
    if not sessions:
        st.markdown(
            '<div class="ck-empty">No conversations yet.<br>Start a new conversation with Clinkey.</div>',
            unsafe_allow_html=True,
        )
    for label, group in _group_sessions(sessions[:40]).items():
        st.markdown(
            f"<div style='font-size:.72rem;text-transform:uppercase;letter-spacing:.04em;"
            f"opacity:.55;margin:.55rem 0 .2rem .2rem;'>{html.escape(label)}</div>",
            unsafe_allow_html=True,
        )
        for s in group:
            title = s.title or "Untitled chat"
            active = s.session_id == SS.session_id
            open_col, menu_col = st.columns([4.4, 0.9], gap="small")
            with open_col:
                prefix = "• " if active else ""
                if st.button(f"{prefix}{title[:40]}", key=f"open_{s.session_id}", use_container_width=True):
                    SS.session_id = s.session_id
                    SS.messages = _messages_from_session(s)
                    st.rerun()
            with menu_col:
                with st.popover("⋮", key=f"menu_{s.session_id}", use_container_width=True):
                    st.markdown(f"**{html.escape(title[:40])}**")
                    new_name = st.text_input("Rename", value=s.title, key=f"rename_{s.session_id}",
                                             label_visibility="collapsed")
                    if st.button("Save name", key=f"save_{s.session_id}", use_container_width=True):
                        repo.rename_session(s.session_id, new_name)
                        st.rerun()
                    if st.button("Delete", key=f"del_{s.session_id}", use_container_width=True):
                        repo.delete_session(s.session_id)
                        if s.session_id == SS.session_id:
                            SS.session_id = ""
                            SS.messages = []
                        st.rerun()

    st.markdown("---")

    # settings
    st.markdown("**Settings**")
    dark = st.toggle("Dark mode", value=SS.dark_mode)
    if dark != SS.dark_mode:
        SS.dark_mode = dark
        st.rerun()

    with st.expander("About"):
        st.markdown(
            "ClinKey is a multilingual medical evidence assistant that answers health "
            "questions using official clinical guidelines."
        )
        st.markdown(
            "- **Languages:** English, Arabic, French, Spanish, German, Italian, Portuguese, "
            "Turkish, Hindi, Urdu, Chinese\n"
            "- **Sources:** WHO, CDC, NICE, USPSTF, NIH, NCBI, IDSA, AHA, ESC, ADA, MedlinePlus, "
            "FDA, EMA, NHS, Cochrane, Health Canada, Australian Department of Health"
        )
        st.caption(settings.app_disclaimer)
        _emb_provider = settings.embeddings_effective_provider
        if _emb_provider == "sentence-transformers":
            st.caption(f"Embeddings: {settings.get('embeddings_model')} (semantic)")
        else:
            st.caption("Embeddings: hash fallback (demo mode — sentence-transformers not installed)")


# ---------------------------------------------------------------- main
if not SS.session_id:
    SS.session_id = uuid.uuid4().hex[:12]
if "messages" not in SS:
    SS.messages = []

has_conversation = any(m["role"] == "user" for m in SS.messages)

if not has_conversation:
    # ---- welcome screen ----
    st.markdown('<div style="height:3rem"></div>', unsafe_allow_html=True)
    _render_welcome()
else:
    # ---- conversation header ----
    st.markdown(
        f"<div class='ck-conv-header'>"
        f"<span class='ck-conv-title'>{html.escape(_conversation_title())}</span>"
        f"<span class='ck-conv-note'>· evidence-grounded · official sources</span>"
        f"</div>",
        unsafe_allow_html=True,
    )

for m in SS.messages:
    if m["role"] == "user":
        with st.chat_message("user"):
            st.markdown(
                f'<div class="ck-msg-user">{html.escape(m["original_text"])}</div>',
                unsafe_allow_html=True,
            )
    else:
        avatar = LOGO_IMAGE if LOGO_IMAGE is not None else None
        with st.chat_message("assistant", avatar=avatar):
            st.markdown(m["localized_answer"])

            badges = []
            if m.get("confidence"):
                badges.append(chip(f"Confidence: {m['confidence']}", confidence_color(m["confidence"])))
            if m.get("safety") and m.get("safety") != "ALLOWED":
                badges.append(chip(f"Safety: {m['safety']}", "#B05A00"))
            if m.get("detected_language") and m.get("detected_language") != "en":
                badges.append(chip(f"Language: {m['detected_language']}", "#0060A0"))
            if badges:
                st.markdown("".join(badges), unsafe_allow_html=True)

            if m.get("citations"):
                with st.expander(f"References ({len(m['citations'])})"):
                    _render_citations(m["citations"])

            if m.get("evidence"):
                with st.expander(f"Evidence panel ({len(m['evidence'])} chunks)"):
                    _render_evidence(m["evidence"])

            if not m.get("is_greeting"):
                st.markdown(
                    f"<div class='ck-disclaimer'>{html.escape(settings.app_disclaimer)}</div>",
                    unsafe_allow_html=True,
                )

# ---------------------------------------------------------------- input bar
with st.form("chat_input", border=False, clear_on_submit=True):
    t_col, s_col = st.columns([9.2, 0.9], gap="small", vertical_alignment="center")
    with t_col:
        prompt = st.text_input(
            "Ask a medical Question", placeholder="Ask a medical Question",
            label_visibility="collapsed", key="chat_input_text",
        )
    with s_col:
        send = st.form_submit_button("➤", type="primary", use_container_width=True)

pending = SS.pop("pending_question", "")

if send or pending:
    question_to_ask = (pending or (prompt or "").strip())
    if question_to_ask:
        _process_question(question_to_ask)